# Generated by Django 6.0.2 on 2026-05-20 10:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_service_categories', to='organizations.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Service category',
                'verbose_name_plural': 'Service categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_client', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Client price')),
                ('real_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Real cost')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Public')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_services', to='organizations.company', verbose_name='Company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_services', to='education.currency', verbose_name='Currency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='erp_services.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('price_client', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Client price')),
                ('real_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Real cost')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid to')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_service_prices', to='education.currency', verbose_name='Currency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='erp_services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service price',
                'verbose_name_plural': 'Service prices',
                'ordering': ['service__title', '-valid_from', 'currency__code'],
            },
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['company', 'is_active'], name='erp_service_company_73edbb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['code'], name='erp_service_code_c2bb12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['company', 'is_active', 'is_public'], name='erp_service_company_5073d5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='erp_service_categor_19f616_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='erp_service_code_ccffd6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['title'], name='erp_service_title_d09c9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['service', 'currency'], name='erp_service_service_b419d6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['valid_from', 'valid_to'], name='erp_service_valid_f_bfe74e_idx'),
        ),
    ]
