# Generated by Django 6.0.2 on 2026-02-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersalary',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Сколько получает менеджер с чистого дохода', max_digits=5, verbose_name='Процент от сделок (%)'),
        ),
    ]
