# Generated by Django 6.0.2 on 2026-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_managersalary_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersalary',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Фиксированный оклад (USD)'),
        ),
        migrations.AddField(
            model_name='managersalary',
            name='motivation_reward',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Сумма бонуса (USD)'),
        ),
        migrations.AddField(
            model_name='managersalary',
            name='motivation_target',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Цель для мотивашки (Выручка USD)'),
        ),
        migrations.AlterField(
            model_name='managersalary',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Процент от сделок (%)'),
        ),
        migrations.AlterField(
            model_name='managersalary',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Накопленные проценты со сделок', max_digits=10, verbose_name='Бонусы к выплате (USD)'),
        ),
    ]
