# Generated by Django 6.0.2 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_managersalary_fixed_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managersalary',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент от сделок (%)'),
        ),
        migrations.AlterField(
            model_name='managersalary',
            name='motivation_reward',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Сумма бонуса (USD)'),
        ),
    ]
