# Generated by Django 6.0.2 on 2026-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_managersalary_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_contacts',
            field=models.CharField(blank=True, help_text='Telegram, Instagram, WhatsApp и т.д.', max_length=255, verbose_name='Контакты в соц. сетях'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
