# Generated by Django 6.0.2 on 2026-04-04 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_plan_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='План офиса на месяц (USD)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к плану')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to='users.office', verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'План офиса',
                'verbose_name_plural': 'Планы офисов',
            },
        ),
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_office_dashboard', models.BooleanField(default=False, verbose_name='Может видеть баланс офиса')),
                ('can_be_in_leaderboard', models.BooleanField(default=True, verbose_name='Показывать в рейтинге')),
                ('managed_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_managers', to='users.office', verbose_name='Управляемый офис')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль доступа менеджера',
                'verbose_name_plural': 'Профили доступа менеджеров',
            },
        ),
    ]
