# Generated by Django 6.0.2 on 2026-05-22 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('entity_key', models.SlugField(blank=True, help_text='Optional non-model entity key, for example client_profile.', max_length=100, verbose_name='Entity key')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('code', models.SlugField(max_length=100, verbose_name='Code')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date and time'), ('select', 'Select'), ('multi_select', 'Multi select'), ('user', 'User'), ('file', 'File'), ('json', 'JSON')], db_index=True, default='text', max_length=32, verbose_name='Field type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='Placeholder')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Help text')),
                ('default_value', models.JSONField(blank=True, default=dict, verbose_name='Default value')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='Validation rules')),
                ('is_required', models.BooleanField(db_index=True, default=False, verbose_name='Required')),
                ('is_filterable', models.BooleanField(db_index=True, default=False, verbose_name='Filterable')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Public')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organizations.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(blank=True, help_text='Optional Django model this field belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_custom_fields', to='contenttypes.contenttype', verbose_name='Target model')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_fields_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Custom field',
                'verbose_name_plural': 'Custom fields',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('value', models.SlugField(max_length=120, verbose_name='Value')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='Color')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='customfields.customfield', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'Custom field option',
                'verbose_name_plural': 'Custom field options',
                'ordering': ['field__name', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Object id')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='Value')),
                ('value_search', models.TextField(blank=True, db_index=True, verbose_name='Search text')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='organizations.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_custom_field_values', to='contenttypes.contenttype', verbose_name='Content type')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customfields.customfield', verbose_name='Field')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='organizations.office', verbose_name='Office')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values_set', to=settings.AUTH_USER_MODEL, verbose_name='Set by')),
            ],
            options={
                'verbose_name': 'Custom field value',
                'verbose_name_plural': 'Custom field values',
                'ordering': ['field__sort_order', 'field__name'],
            },
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['company', 'office', 'is_active'], name='customfield_company_73897d_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['content_type', 'entity_key'], name='customfield_content_22e70d_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['field_type', 'is_required'], name='customfield_field_t_491b30_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['code'], name='customfield_code_a8fe94_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['name'], name='customfield_name_346a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('company', 'office', 'content_type', 'entity_key', 'code')},
        ),
        migrations.AddIndex(
            model_name='customfieldoption',
            index=models.Index(fields=['field', 'is_active'], name='customfield_field_i_56ce3f_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldoption',
            index=models.Index(fields=['value'], name='customfield_value_4c0dd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldoption',
            unique_together={('field', 'value')},
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['company', 'office'], name='customfield_company_0a4783_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['content_type', 'object_id'], name='customfield_content_311bed_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['field', 'object_id'], name='customfield_field_i_4d164f_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['set_by', 'created_at'], name='customfield_set_by__5db030_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('field', 'content_type', 'object_id')},
        ),
    ]
