# Generated by Django 6.0.2 on 2026-03-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('category', models.CharField(choices=[('info', 'Информационное'), ('promo', 'Акция / Предложение'), ('reminder', 'Напоминание'), ('welcome', 'Приветственное'), ('custom', 'Произвольное')], default='custom', max_length=20, verbose_name='Категория')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body_html', models.TextField(help_text='Используйте {{first_name}}, {{last_name}}, {{email}}, {{office}} как переменные', verbose_name='HTML-тело письма')),
                ('body_text', models.TextField(blank=True, help_text='Отображается если HTML не поддерживается', verbose_name='Текстовое тело (запасной вариант)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('recipient_type', models.CharField(choices=[('all_clients', 'Все клиенты'), ('all_staff', 'Все сотрудники'), ('clients_status', 'Клиенты по статусу'), ('custom_emails', 'Произвольные email-адреса')], default='all_clients', max_length=30, verbose_name='Тип получателей')),
                ('client_status', models.CharField(blank=True, help_text='Заполнять при типе "Клиенты по статусу"', max_length=20, verbose_name='Статус клиентов')),
                ('custom_emails', models.TextField(blank=True, verbose_name='Произвольные email (через запятую или перенос строки)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('done', 'Завершена'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Отправлено писем')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='Ошибок отправки')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mailing.emailtemplate', verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Имя получателя')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_msg', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailingcampaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Лог отправки',
                'verbose_name_plural': 'История отправок',
                'ordering': ['-sent_at'],
            },
        ),
    ]
