# Generated by Django 6.0.2 on 2026-03-25 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_address_registration_client_citizenship_and_more'),
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='specific_clients',
            field=models.ManyToManyField(blank=True, to='clients.client', verbose_name='Конкретные клиенты'),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='specific_staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Конкретные сотрудники'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='recipient_type',
            field=models.CharField(choices=[('all_clients', 'Все клиенты (Вся база)'), ('all_staff', 'Все сотрудники (Вся команда)'), ('specific_clients', 'Выбрать клиентов вручную'), ('specific_staff', 'Выбрать сотрудников вручную'), ('clients_status', 'Клиенты по статусу'), ('custom_emails', 'Ввести любые email вручную')], default='all_clients', max_length=30, verbose_name='Тип получателей'),
        ),
    ]
