# Generated by Django 6.0.2 on 2026-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='Образование')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('relation', models.CharField(blank=True, help_text='Например: Сам, Родитель, Брат', max_length=100, verbose_name='Родство')),
                ('direction', models.CharField(blank=True, help_text='Желаемая программа/ВУЗ', max_length=255, verbose_name='Направление')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Взят в работу'), ('converted', 'Стал клиентом'), ('rejected', 'Отказ/Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка с сайта',
                'verbose_name_plural': 'Заявки с сайта',
                'ordering': ['-created_at'],
            },
        ),
    ]
