# Generated by Django 6.0.2 on 2026-02-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='direction',
            field=models.CharField(blank=True, choices=[('admission', 'Поступление'), ('translation', 'Переводы'), ('umrah', 'Умра/Хадж'), ('visa', 'Виза'), ('tickets', 'Билеты'), ('tours', 'Туры в Туркменистан'), ('work_visa', 'Рабочие визы')], max_length=50, verbose_name='Направление'),
        ),
    ]
