# Generated by Django 6.0.2 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_manager_alter_lead_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='arrival_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город прибытия'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текущая страна'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текущее образование'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_university',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текущий университет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город вылета'),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_passport',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наличие паспорта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='luggage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Багаж'),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО родителя'),
        ),
        migrations.AddField(
            model_name='lead',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия паспорта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поездки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_month',
            field=models.CharField(blank=True, max_length=50, verbose_name='Месяц поездки'),
        ),
    ]
