# Generated by Django 6.0.2 on 2026-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_arrival_city_lead_current_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
