# Generated by Django 6.0.2 on 2026-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='submitter_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitter_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP отправителя'),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitter_origin',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitter_referer',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitter_user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User-Agent отправителя'),
        ),
    ]
