# Generated by Django 6.0.2 on 2026-02-14 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('university', 'Поступление в ВУЗ'), ('service', 'Доп. услуга (Виза/Билет)')], max_length=20, verbose_name='Тип сделки')),
                ('custom_service_name', models.CharField(blank=True, max_length=255, verbose_name='Название услуги (Ручное)')),
                ('custom_service_desc', models.TextField(blank=True, verbose_name='Описание действий менеджера')),
                ('price_client', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена для клиента (в валюте)')),
                ('expected_revenue_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ожидаемая выручка компании (USD)')),
                ('total_to_pay_usd', models.DecimalField(decimal_places=2, help_text='Авто-конвертация', max_digits=12, verbose_name='Итого к оплате (USD)')),
                ('paid_amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Уже оплачено (USD)')),
                ('payment_status', models.CharField(choices=[('new', 'Новая'), ('process', 'В процессе'), ('waiting_payment', 'Ожидает оплаты'), ('paid_partial', 'Частично оплачена'), ('paid_full', 'Полностью оплачена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Сумма в USD')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Расход фирмы',
                'verbose_name_plural': 'Расходы фирмы',
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Всего выручка (USD)')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Всего расходы (USD)')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Чистая прибыль (Котёл)')),
                ('is_closed', models.BooleanField(default=False, help_text='Если закрыт - зарплаты выплачены/обнулены', verbose_name='Период закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Финансовый отчет (Период)',
                'verbose_name_plural': 'Финансовые отчеты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('exchange_rate', models.DecimalField(decimal_places=4, editable=False, max_digits=10, verbose_name='Курс конвертации')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Сумма в USD')),
                ('net_income_usd', models.DecimalField(decimal_places=2, help_text='Сколько реально заработали за вычетом расходов вуза и т.д.', max_digits=12, verbose_name='Чистый доход компании с платежа (USD)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank', 'Банковский перевод')], max_length=20, verbose_name='Способ оплаты')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено Администрацией')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
