# Generated by Django 6.0.2 on 2026-02-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.currency', verbose_name='Валюта сделки'),
        ),
    ]
