# Generated by Django 6.0.2 on 2026-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialperiod',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Чистая прибыль (Котёл)'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Всего расходы (USD)'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Всего выручка (USD)'),
        ),
    ]
