# Generated by Django 6.0.2 on 2026-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_financialperiod_net_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='net_income_usd',
            field=models.DecimalField(decimal_places=2, help_text='Сколько реально заработали', max_digits=12, verbose_name='Чистый доход компании с платежа (USD)'),
        ),
    ]
