# Generated by Django 6.0.2 on 2026-02-17 20:27

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('analytics', '0006_alter_financialperiod_start_date_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
            ],
            options={
                'verbose_name': 'История действий',
                'verbose_name_plural': 'История действий',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
