# Generated by Django 6.0.2 on 2026-04-04 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_expense_updated_at_financialperiod_updated_at_and_more'),
        ('catalog', '0007_currency_updated_at_program_updated_at_and_more'),
        ('users', '0007_officetarget_useraccessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('university', 'Поступление'), ('service', 'Услуга')], max_length=20, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='payment_status',
            field=models.CharField(choices=[('new', 'Новая'), ('paid_partial', 'Частично оплачено'), ('paid_full', 'Оплачено полностью')], default='new', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Сумма в USD'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, editable=False, max_digits=10, verbose_name='Курс конвертации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_income_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сколько реально заработали', max_digits=12, verbose_name='Чистый доход компании с платежа (USD)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.CreateModel(
            name='OfficeFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], db_index=True, max_length=20, verbose_name='Тип операции')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Курс к USD')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма в USD')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата операции')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_finance_entries', to='catalog.currency', verbose_name='Валюта')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='users.office', verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'Офисная финансовая операция',
                'verbose_name_plural': 'Офисные финансовые операции',
                'ordering': ('-entry_date', '-created_at'),
            },
        ),
    ]
