# Generated by Django 6.0.2 on 2026-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_deal_deal_type_alter_deal_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officefinanceentry',
            name='category',
            field=models.CharField(choices=[('custom', 'Другое'), ('salary', 'Зарплата'), ('visa', 'Виза'), ('air_tickets', 'Авиабилеты'), ('office', 'Офис'), ('utilities', 'Коммунальные расходы'), ('marketing', 'Маркетинг')], db_index=True, default='custom', max_length=100, verbose_name='Категория'),
        ),
    ]
