# Generated by Django 6.0.2 on 2026-05-20 10:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_application_crm_applica_company_585004_idx_and_more'),
        ('education', '0001_initial'),
        ('erp_services', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Balance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_cashboxes', to='organizations.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_cashboxes', to='education.currency', verbose_name='Currency')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_cashboxes', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Cashbox',
                'verbose_name_plural': 'Cashboxes',
                'ordering': ['company__name', 'office__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('deal_type', models.CharField(choices=[('university', 'University'), ('service', 'Service'), ('other', 'Other')], db_index=True, default='service', max_length=32, verbose_name='Deal type')),
                ('university_name', models.CharField(blank=True, max_length=255, verbose_name='University name')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='Program name')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('price_client', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Client price')),
                ('expected_revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Expected revenue USD')),
                ('total_to_pay_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total to pay USD')),
                ('paid_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Paid amount USD')),
                ('payment_status', models.CharField(choices=[('new', 'New'), ('paid_partial', 'Partially paid'), ('paid_full', 'Paid in full'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=32, verbose_name='Payment status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deals', to='crm.application', verbose_name='Application')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_deals', to='crm.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_deals', to='organizations.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_deals', to='education.currency', verbose_name='Currency')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_deals', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deals', to='organizations.office', verbose_name='Office')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deals', to='erp_services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_expense_categories', to='organizations.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Expense category',
                'verbose_name_plural': 'Expense categories',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='Exchange rate to USD')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount USD')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='Confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.cashbox', verbose_name='Cashbox')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to='organizations.company', verbose_name='Company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_finance_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to='education.currency', verbose_name='Currency')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to='organizations.office', verbose_name='Office')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End date')),
                ('total_revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total revenue USD')),
                ('total_expenses_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total expenses USD')),
                ('net_profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Net profit USD')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Closed')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_finance_periods', to=settings.AUTH_USER_MODEL, verbose_name='Closed by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_periods', to='organizations.company', verbose_name='Company')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_periods', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Financial period',
                'verbose_name_plural': 'Financial periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='Exchange rate to USD')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount USD')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.cashbox', verbose_name='Cashbox')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_incomes', to='organizations.company', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_incomes', to='education.currency', verbose_name='Currency')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='Exchange rate to USD')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount USD')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('transfer', 'Transfer'), ('online', 'Online'), ('other', 'Other')], db_index=True, default='cash', max_length=32, verbose_name='Method')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Payment date')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='Confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.cashbox', verbose_name='Cashbox')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='crm.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='organizations.company', verbose_name='Company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_finance_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='education.currency', verbose_name='Currency')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.deal', verbose_name='Deal')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Percent')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount USD')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_commissions', to='organizations.company', verbose_name='Company')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='finance.deal', verbose_name='Deal')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_commissions', to='organizations.office', verbose_name='Office')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='finance.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Employee commission',
                'verbose_name_plural': 'Employee commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('payment', 'Payment'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('correction', 'Correction')], db_index=True, max_length=32, verbose_name='Transaction type')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount USD')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashbox', verbose_name='Cashbox')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='education.currency', verbose_name='Currency')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='organizations.office', verbose_name='Office')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.expense', verbose_name='Related expense')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.payment', verbose_name='Related payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['company', 'office', 'is_active'], name='finance_cas_company_794a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashbox',
            unique_together={('company', 'office', 'name')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'office', 'payment_status'], name='finance_dea_company_b16e99_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['manager', 'payment_status'], name='finance_dea_manager_cd4fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'payment_status'], name='finance_dea_client__3e7761_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_type'], name='finance_dea_deal_ty_fe15e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='finance_dea_created_8a7451_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['company', 'is_active'], name='finance_exp_company_68737e_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['code'], name='finance_exp_code_77dda4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'office', 'is_confirmed'], name='finance_exp_company_9696ea_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['employee', 'date'], name='finance_exp_employe_e8cfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finance_exp_date_677539_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['company', 'office', 'is_closed'], name='finance_fin_company_d041b6_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='finance_fin_start_d_5e26fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialperiod',
            unique_together={('company', 'office', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['company', 'office', 'date'], name='finance_inc_company_b61e92_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date'], name='finance_inc_date_8372c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'office', 'is_confirmed'], name='finance_pay_company_de3525_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['manager', 'payment_date'], name='finance_pay_manager_df9d54_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'payment_date'], name='finance_pay_client__279208_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='finance_pay_payment_72f761_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecommission',
            index=models.Index(fields=['company', 'office', 'status'], name='finance_emp_company_c9074d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecommission',
            index=models.Index(fields=['employee', 'status'], name='finance_emp_employe_61bbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'office', 'transaction_type'], name='finance_tra_company_0fc95a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['cashbox', 'created_at'], name='finance_tra_cashbox_979a83_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='finance_tra_created_ef4f06_idx'),
        ),
    ]
