# Generated by Django 6.0.2 on 2026-05-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_current_education_client_current_school_and_more'),
        ('education', '0001_initial'),
        ('erp_services', '0002_service_created_by_service_updated_by'),
        ('finance', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='finance_inc_company_b61e92_idx',
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='finance.income', verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='income',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='crm.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='income',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at'),
        ),
        migrations.AddField(
            model_name='income',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_finance_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by'),
        ),
        migrations.AddField(
            model_name='income',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='finance.deal', verbose_name='Deal'),
        ),
        migrations.AddField(
            model_name='income',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='income',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/income_proofs/', verbose_name='Proof file'),
        ),
        migrations.AddField(
            model_name='income',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected at'),
        ),
        migrations.AddField(
            model_name='income',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_finance_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by'),
        ),
        migrations.AddField(
            model_name='income',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection reason'),
        ),
        migrations.AddField(
            model_name='income',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='erp_services.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.income', verbose_name='Related income'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='finance.deal', verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='employeecommission',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='finance.payment', verbose_name='Payment'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['company', 'office', 'status'], name='finance_inc_company_32f3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['employee', 'date'], name='finance_inc_employe_b8e226_idx'),
        ),
    ]
