# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_income_finance_inc_company_b61e92_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/payment_proofs/', verbose_name='Proof file'),
        ),
        migrations.AddField(
            model_name='expense',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/expense_proofs/', verbose_name='Proof file'),
        ),
    ]
