# Generated by Django 6.0.2 on 2026-05-20 11:03

import apps.erp_documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_application_crm_applica_company_585004_idx_and_more'),
        ('finance', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('code', models.SlugField(max_length=100, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=apps.erp_documents.models.template_upload_path, verbose_name='DOCX template')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires approval')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_document_templates', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Document template',
                'verbose_name_plural': 'Document templates',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('key', models.SlugField(max_length=100, verbose_name='Key')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select')], default='text', max_length=32, verbose_name='Field type')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Default value')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Help text')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='erp_documents.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Document template field',
                'verbose_name_plural': 'Document template fields',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Context data')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Generation error')], db_index=True, default='draft', max_length=32, verbose_name='Status')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to=apps.erp_documents.models.generated_upload_path, verbose_name='Generated DOCX')),
                ('approved_file', models.FileField(blank=True, null=True, upload_to=apps.erp_documents.models.approved_upload_path, verbose_name='Approved DOCX')),
                ('generation_error', models.TextField(blank=True, verbose_name='Generation error')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='crm.application', verbose_name='Application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_documents_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to='crm.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to='organizations.company', verbose_name='Company')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='finance.deal', verbose_name='Deal')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='organizations.office', verbose_name='Office')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='erp_documents.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Generated document',
                'verbose_name_plural': 'Generated documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('original', 'Original'), ('approved', 'Approved')], max_length=32, verbose_name='File type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_download_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='erp_documents.generateddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document download log',
                'verbose_name_plural': 'Document download logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32, verbose_name='Status')),
                ('approval_type', models.CharField(choices=[('not_selected', 'Not selected'), ('without_stamp', 'Approve without stamp'), ('with_stamp', 'Approve with stamp')], default='not_selected', max_length=32, verbose_name='Approval type')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='erp_documents.generateddocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document approval',
                'verbose_name_plural': 'Document approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('stamp_image', models.ImageField(upload_to=apps.erp_documents.models.stamp_upload_path, verbose_name='Stamp image')),
                ('width_mm', models.PositiveIntegerField(default=40, verbose_name='Width, mm')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_document_stamp_rules', to='organizations.company', verbose_name='Company')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_document_stamp_rules', to='organizations.office', verbose_name='Office')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamp_rules', to='erp_documents.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Stamp rule',
                'verbose_name_plural': 'Stamp rules',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['company', 'is_active'], name='erp_documen_company_63a5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['code'], name='erp_documen_code_32a39a_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['name'], name='erp_documen_name_aa3cf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='documenttemplatefield',
            index=models.Index(fields=['template', 'sort_order'], name='erp_documen_templat_6e80c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplatefield',
            unique_together={('template', 'key')},
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['company', 'office', 'status'], name='erp_documen_company_7992cb_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['manager', 'status'], name='erp_documen_manager_35acfa_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['client', 'status'], name='erp_documen_client__0feef5_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['created_at'], name='erp_documen_created_53c3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownloadlog',
            index=models.Index(fields=['document', 'file_type'], name='erp_documen_documen_7bdd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownloadlog',
            index=models.Index(fields=['user', 'created_at'], name='erp_documen_user_id_16b030_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['status', 'reviewed_at'], name='erp_documen_status_dfba4d_idx'),
        ),
        migrations.AddIndex(
            model_name='stamprule',
            index=models.Index(fields=['company', 'office', 'is_active'], name='erp_documen_company_21cebb_idx'),
        ),
        migrations.AddIndex(
            model_name='stamprule',
            index=models.Index(fields=['template', 'is_active'], name='erp_documen_templat_52fcd3_idx'),
        ),
    ]
