# Generated by Django 6.0.2 on 2026-05-24 05:34

import apps.erp_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='allow_with_stamp',
            field=models.BooleanField(default=True, verbose_name='Allow PDF with stamp'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='allow_without_stamp',
            field=models.BooleanField(default=True, verbose_name='Allow DOCX without stamp'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='jinja_variables',
            field=models.JSONField(blank=True, default=list, verbose_name='Jinja variables'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='stamp_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Stamp settings'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='watermark_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Watermark settings'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='data_source',
            field=models.CharField(choices=[('client', 'Client'), ('application', 'Application'), ('deal', 'Deal'), ('manager', 'Manager'), ('company', 'Company'), ('office', 'Office'), ('custom', 'Custom')], db_index=True, default='custom', max_length=32, verbose_name='Data source'),
        ),
        migrations.AddField(
            model_name='documenttemplatefield',
            name='jinja_key',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jinja key'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='height_mm',
            field=models.PositiveIntegerField(default=40, verbose_name='Height, mm'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Opacity'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='position',
            field=models.CharField(choices=[('bottom_left', 'Bottom left'), ('bottom_right', 'Bottom right'), ('top_left', 'Top left'), ('top_right', 'Top right'), ('center', 'Center'), ('custom', 'Custom')], default='bottom_left', max_length=32, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_enabled',
            field=models.BooleanField(default=False, verbose_name='Watermark enabled'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.erp_documents.models.stamp_upload_path, verbose_name='Watermark image'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_opacity',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4, verbose_name='Watermark opacity'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_position',
            field=models.CharField(choices=[('bottom_left', 'Bottom left'), ('bottom_right', 'Bottom right'), ('top_left', 'Top left'), ('top_right', 'Top right'), ('center', 'Center'), ('custom', 'Custom')], default='center', max_length=32, verbose_name='Watermark position'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Watermark text'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='x_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='X, mm'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='y_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Y, mm'),
        ),
    ]
