# Generated by Django 6.0.2 on 2026-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_documents', '0002_documenttemplate_allow_with_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamprule',
            name='watermark_height_mm',
            field=models.PositiveIntegerField(default=60, verbose_name='Watermark height, mm'),
        ),
        migrations.AddField(
            model_name='stamprule',
            name='watermark_width_mm',
            field=models.PositiveIntegerField(default=160, verbose_name='Watermark width, mm'),
        ),
    ]
