# Generated by Django 6.0.2 on 2026-06-04 07:05

import apps.erp_documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_api_source_lead_archive_reason_lead_archived_at_and_more'),
        ('erp_documents', '0003_stamprule_watermark_height_mm_and_more'),
        ('finance', '0003_payment_expense_proof_files'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentapproval',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подтверждение документа', 'verbose_name_plural': 'Подтверждения документов'},
        ),
        migrations.AlterModelOptions(
            name='documentdownloadlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог скачивания документа', 'verbose_name_plural': 'Логи скачивания документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplatefield',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Поле шаблона документа', 'verbose_name_plural': 'Поля шаблонов документов'},
        ),
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сгенерированный документ', 'verbose_name_plural': 'Сгенерированные документы'},
        ),
        migrations.AlterModelOptions(
            name='stamprule',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Правило электронной печати', 'verbose_name_plural': 'Правила электронной печати'},
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='approval_type',
            field=models.CharField(choices=[('not_selected', 'Не выбрано'), ('without_stamp', 'Одобрить без печати'), ('with_stamp', 'Одобрить с электронной печатью')], default='not_selected', max_length=32, verbose_name='Тип подтверждения'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='erp_documents.generateddocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверено'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата скачивания'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='erp_documents.generateddocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='file_type',
            field=models.CharField(choices=[('original', 'DOCX без печати'), ('approved', 'PDF с печатью')], max_length=32, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_download_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='allow_with_stamp',
            field=models.BooleanField(default=True, verbose_name='Разрешить скачать PDF с печатью'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='allow_without_stamp',
            field=models.BooleanField(default=True, verbose_name='Разрешить скачать DOCX без печати'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='code',
            field=models.SlugField(max_length=100, verbose_name='Код шаблона'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_document_templates', to='organizations.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_document_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(upload_to=apps.erp_documents.models.template_upload_path, verbose_name='DOCX-файл шаблона'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='jinja_variables',
            field=models.JSONField(blank=True, default=list, verbose_name='Jinja-переменные'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='Требуется подтверждение администратора'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='stamp_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Технические настройки печати'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='watermark_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Технические настройки водяного знака'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='data_source',
            field=models.CharField(choices=[('client', 'Клиент'), ('application', 'Заявка'), ('deal', 'Сделка'), ('manager', 'Менеджер'), ('company', 'Компания'), ('office', 'Офис'), ('custom', 'Свое значение')], db_index=True, default='custom', max_length=32, verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('textarea', 'Большой текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/нет'), ('select', 'Выбор')], default='text', max_length=32, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное поле'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='jinja_key',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jinja-ключ'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='key',
            field=models.SlugField(max_length=100, verbose_name='Ключ поля'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='documenttemplatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='erp_documents.documenttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='crm.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_documents_approved', to=settings.AUTH_USER_MODEL, verbose_name='Кем одобрен'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='approved_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.erp_documents.models.approved_upload_path, verbose_name='PDF с печатью / одобренный файл'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to='crm.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to='organizations.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные для подстановки'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='finance.deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сгенерирован'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.erp_documents.models.generated_upload_path, verbose_name='DOCX без печати'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='generation_error',
            field=models.TextField(blank=True, verbose_name='Ошибка генерации'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_generated_documents', to='organizations.office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сгенерирован'), ('pending', 'Ожидает подтверждения'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('error', 'Ошибка генерации')], db_index=True, default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен на подтверждение'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='erp_documents.documenttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_document_stamp_rules', to='organizations.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='height_mm',
            field=models.PositiveIntegerField(default=40, verbose_name='Высота печати, мм'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название правила'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_document_stamp_rules', to='organizations.office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Прозрачность печати'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='position',
            field=models.CharField(choices=[('bottom_left', 'Снизу слева'), ('bottom_right', 'Снизу справа'), ('top_left', 'Сверху слева'), ('top_right', 'Сверху справа'), ('center', 'По центру'), ('custom', 'Своя позиция')], default='bottom_left', max_length=32, verbose_name='Позиция печати'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='stamp_image',
            field=models.ImageField(upload_to=apps.erp_documents.models.stamp_upload_path, verbose_name='Файл электронной печати'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamp_rules', to='erp_documents.documenttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить водяной знак'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_height_mm',
            field=models.PositiveIntegerField(default=60, verbose_name='Высота водяного знака, мм'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.erp_documents.models.stamp_upload_path, verbose_name='Изображение водяного знака'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_opacity',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4, verbose_name='Прозрачность водяного знака'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_position',
            field=models.CharField(choices=[('bottom_left', 'Снизу слева'), ('bottom_right', 'Снизу справа'), ('top_left', 'Сверху слева'), ('top_right', 'Сверху справа'), ('center', 'По центру'), ('custom', 'Своя позиция')], default='center', max_length=32, verbose_name='Позиция водяного знака'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст водяного знака'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='watermark_width_mm',
            field=models.PositiveIntegerField(default=160, verbose_name='Ширина водяного знака, мм'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='width_mm',
            field=models.PositiveIntegerField(default=40, verbose_name='Ширина печати, мм'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='x_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Координата X, мм'),
        ),
        migrations.AlterField(
            model_name='stamprule',
            name='y_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Координата Y, мм'),
        ),
    ]
