# Generated by Django 6.0.2 on 2026-06-04 17:23

import apps.erp_documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_documents', '0004_alter_documentapproval_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='stamp_preview_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.erp_documents.models.stamp_preview_upload_path, verbose_name='Предпросмотр PDF с печатью'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='stamp_preview_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предпросмотр печати создан'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='stamp_preview_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_documents_stamp_previews', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан предпросмотр печати'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='stamp_preview_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки предпросмотра печати'),
        ),
    ]
