# Generated by Django 6.0.2 on 2026-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_client', models.DecimalField(decimal_places=2, help_text='Эту цену видит менеджер', max_digits=10, verbose_name='Цена для клиента (USD)')),
                ('real_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Реальная цена услуги. НЕ ПОКАЗЫВАТЬ МЕНЕДЖЕРАМ.', max_digits=10, verbose_name='Себестоимость (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга (Каталог)',
                'verbose_name_plural': 'Услуги (Каталог)',
            },
        ),
    ]
