# Generated by Django 6.0.2 on 2026-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО Клиента')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('consultation', 'Консультация'), ('documents', 'Сбор документов'), ('visa', 'Виза'), ('success', 'Завершен (Успех)'), ('rejected', 'Отказ'), ('archive', 'Архив (Авто)')], default='new', max_length=20, verbose_name='Статус')),
                ('is_priority', models.BooleanField(default=False, help_text='Если нет, клиент может уйти в архив автоматически', verbose_name='Приоритетный клиент')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('passport_local_num', models.CharField(blank=True, max_length=50, verbose_name='Серия внутреннего паспорта')),
                ('passport_inter_num', models.CharField(blank=True, max_length=50, verbose_name='Серия загранпаспорта')),
                ('current_tasks', models.TextField(blank=True, verbose_name='Текущие задачи')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('is_partner_client', models.BooleanField(default=False, verbose_name='От партнера?')),
                ('partner_name', models.CharField(blank=True, max_length=255, verbose_name='Название партнера')),
                ('has_discount', models.BooleanField(default=False, verbose_name='Есть скидка?')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка на услуги (USD)', max_digits=10, verbose_name='Сумма/Процент скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('relation_type', models.CharField(help_text='Отец, Мать, Брат...', max_length=100, verbose_name='Кем приходится')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('work_place', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
            ],
        ),
    ]
