# Generated by Django 6.0.2 on 2026-02-14 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_clients', to=settings.AUTH_USER_MODEL, verbose_name='Основной менеджер'),
        ),
        migrations.AddField(
            model_name='client',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_clients', to=settings.AUTH_USER_MODEL, verbose_name='Доступ открыт также для'),
        ),
        migrations.AddField(
            model_name='clientrelative',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='clients.client'),
        ),
    ]
