# Generated by Django 6.0.2 on 2026-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_registration',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации (Прописка)'),
        ),
        migrations.AddField(
            model_name='client',
            name='citizenship',
            field=models.CharField(default='Туркменистан', max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_by',
            field=models.CharField(blank=True, help_text='Например: МВД Туркменистана', max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_inter_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер загранпаспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_local_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='Серия/Номер внутреннего паспорта'),
        ),
    ]
