# Generated by Django 6.0.2 on 2026-05-22 09:21

import apps.knowledge.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('code', models.SlugField(max_length=100, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='Color')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Public')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_categories', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.knowledgecategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Knowledge category',
                'verbose_name_plural': 'Knowledge categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32, verbose_name='Status')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Public')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_authored', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='organizations.company', verbose_name='Company')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='organizations.office', verbose_name='Office')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.knowledgecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Knowledge article',
                'verbose_name_plural': 'Knowledge articles',
                'ordering': ['-is_featured', '-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pass_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, verbose_name='Pass percent')),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 means unlimited attempts.', verbose_name='Max attempts')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 means no time limit.', verbose_name='Time limit, minutes')),
                ('is_required', models.BooleanField(db_index=True, default=False, verbose_name='Required')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Public')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='knowledge.knowledgearticle', verbose_name='Article')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_tests', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_tests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_tests', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Knowledge test',
                'verbose_name_plural': 'Knowledge tests',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('boolean', 'Boolean')], default='single_choice', max_length=32, verbose_name='Question type')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('correct_answer', models.JSONField(blank=True, default=dict, verbose_name='Correct answer')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Points')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.knowledgetest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Knowledge question',
                'verbose_name_plural': 'Knowledge questions',
                'ordering': ['test__title', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted')], db_index=True, default='started', max_length=32, verbose_name='Status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Answers')),
                ('score_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Score points')),
                ('max_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Max points')),
                ('score_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Score percent')),
                ('is_passed', models.BooleanField(db_index=True, default=False, verbose_name='Passed')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knowledge.knowledgetest', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_knowledge_test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Knowledge test attempt',
                'verbose_name_plural': 'Knowledge test attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('read_count', models.PositiveIntegerField(default=1, verbose_name='Read count')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last read at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_read_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='knowledge.knowledgearticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article read log',
                'verbose_name_plural': 'Article read logs',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['article', 'user'], name='knowledge_a_article_7ad40a_idx'), models.Index(fields=['user', 'last_read_at'], name='knowledge_a_user_id_f4ca04_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('link', 'Link'), ('video', 'Video')], default='file', max_length=32, verbose_name='Attachment type')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.knowledge.models.knowledge_attachment_upload_path, verbose_name='File')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.knowledgearticle', verbose_name='Article')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Knowledge attachment',
                'verbose_name_plural': 'Knowledge attachments',
                'ordering': ['article__title', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['article', 'sort_order'], name='knowledge_k_article_c2a6c0_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='knowledge_k_uploade_d6b112_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgecategory',
            index=models.Index(fields=['company', 'is_active', 'is_public'], name='knowledge_k_company_3db300_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecategory',
            index=models.Index(fields=['parent', 'sort_order'], name='knowledge_k_parent__69e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecategory',
            index=models.Index(fields=['name'], name='knowledge_k_name_0a1acf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgecategory',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['company', 'office', 'status'], name='knowledge_k_company_f0c755_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category', 'status'], name='knowledge_k_categor_0b7ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['is_active', 'is_public'], name='knowledge_k_is_acti_f6f715_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['title'], name='knowledge_k_title_6d91f1_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['published_at'], name='knowledge_k_publish_0e38e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticle',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='knowledgetest',
            index=models.Index(fields=['company', 'office', 'is_active'], name='knowledge_k_company_7ee075_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetest',
            index=models.Index(fields=['article', 'is_active'], name='knowledge_k_article_8a9fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetest',
            index=models.Index(fields=['is_required', 'is_public'], name='knowledge_k_is_requ_b969be_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetest',
            index=models.Index(fields=['title'], name='knowledge_k_title_bf11e0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgequestion',
            index=models.Index(fields=['test', 'is_active'], name='knowledge_k_test_id_099390_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgequestion',
            index=models.Index(fields=['sort_order'], name='knowledge_k_sort_or_15a0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetestattempt',
            index=models.Index(fields=['test', 'user', 'status'], name='knowledge_k_test_id_14b17a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetestattempt',
            index=models.Index(fields=['user', 'is_passed'], name='knowledge_k_user_id_57c219_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetestattempt',
            index=models.Index(fields=['created_at'], name='knowledge_k_created_013198_idx'),
        ),
    ]
