# Generated by Django 6.0.2 on 2026-05-24 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('visibility', models.CharField(choices=[('private', 'Только мне'), ('office', 'Офис'), ('company', 'Вся компания')], db_index=True, default='private', max_length=32, verbose_name='Видимость')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_calendar_events', to='organizations.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_calendar_events_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_calendar_events', to='organizations.office', verbose_name='Офис')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец события')),
                ('participants', models.ManyToManyField(blank=True, related_name='portal_calendar_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['event_date', 'start_time', 'title'],
                'indexes': [models.Index(fields=['company', 'office', 'event_date'], name='portal_cale_company_c19da4_idx'), models.Index(fields=['owner', 'event_date'], name='portal_cale_owner_i_096b25_idx'), models.Index(fields=['visibility', 'event_date'], name='portal_cale_visibil_687974_idx')],
            },
        ),
    ]
