# Generated by Django 6.0.2 on 2026-02-22 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отчета')),
                ('content', models.TextField(verbose_name='Что проделано за день')),
                ('leads_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано новых заявок')),
                ('deals_closed', models.PositiveIntegerField(default=0, verbose_name='Закрыто сделок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ежедневный отчет',
                'verbose_name_plural': 'Ежедневные отчеты',
                'ordering': ['-date'],
            },
        ),
    ]
