# Generated by Django 6.0.2 on 2026-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
