# Generated by Django 6.0.2 on 2026-03-25 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Ежедневный отчет', 'verbose_name_plural': 'Ежедневные отчеты'},
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Расход за день (USD)'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Доход за день (USD)'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_report_per_employee_per_day'),
        ),
    ]
