# Generated by Django 6.0.2 on 2026-02-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_program_service_fee'),
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('file', models.FileField(upload_to='templates/contracts/', verbose_name='Файл шаблона (.docx)')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
            },
        ),
        migrations.CreateModel(
            name='InfoSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('script', 'Скрипты продаж'), ('faq', 'Ответы на частые вопросы'), ('requisites', 'Реквизиты и Счета'), ('links', 'Полезные ссылки')], max_length=50, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание (Текст для копирования)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Быстрый ответ / Инфо',
                'verbose_name_plural': 'База знаний',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик (На проверке)'), ('approved', 'Одобрено (Готов к скачиванию)'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_contracts/', verbose_name='Готовый файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.program', verbose_name='Программа обучения')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.contracttemplate', verbose_name='Выберите шаблон')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
