# Generated by Django 6.0.2 on 2026-02-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_program_service_fee'),
        ('clients', '0003_client_address_registration_client_citizenship_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор / Документ', 'verbose_name_plural': 'Документооборот'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='infosnippet',
            options={'ordering': ['category', 'order'], 'verbose_name': 'База знаний', 'verbose_name_plural': 'База знаний'},
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость (если отличается от программы)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации Заказчика'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_fio',
            field=models.CharField(blank=True, help_text='Если пусто, подставится ФИО студента', max_length=255, verbose_name='ФИО Заказчика (Плательщика)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта Заказчика'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_passport',
            field=models.CharField(blank=True, max_length=100, verbose_name='Паспорт Заказчика'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок оплаты (до какого числа)'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='type',
            field=models.CharField(choices=[('education', 'Обучение (Студент)'), ('work', 'Рабочая виза'), ('consent', 'Согласие на обработку')], default='education', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Студент/Клиент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.program', verbose_name='Программа (для цены)'),
        ),
        migrations.AlterField(
            model_name='infosnippet',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
