# Generated by Django 6.0.2 on 2026-02-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='type',
            field=models.CharField(choices=[('education_budget', 'Обучение (Бюджет)'), ('education_contract', 'Обучение (Контракт)'), ('work', 'Рабочая виза'), ('consent', 'Согласие на обработку')], default='education_contract', max_length=30, verbose_name='Тип документа'),
        ),
    ]
