# Generated by Django 6.0.2 on 2026-02-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_contracttemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infosnippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
