# Generated by Django 6.0.2 on 2026-03-12 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_contract_updated_at_contracttemplate_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание для менеджера')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Файл шаблона (DOCX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название документа (для удобства)')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Введенные данные (Переменные)')),
                ('status', models.CharField(choices=[('draft', 'Создан / Ожидает'), ('generated', 'Сгенерирован'), ('error', 'Ошибка генерации')], default='draft', max_length=20, verbose_name='Статус')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_docs/', verbose_name='Готовый документ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_documents', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Например: client_fio (на английском, без пробелов)', max_length=50, verbose_name='Ключ (как в docx)')),
                ('label', models.CharField(help_text='Например: ФИО Клиента', max_length=255, verbose_name='Название поля (для менеджера)')),
                ('field_type', models.CharField(choices=[('text', 'Строка текста'), ('numeric', 'Число'), ('date', 'Дата'), ('textarea', 'Большой текст')], default='text', max_length=20, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблона',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
    ]
