# Generated by Django 6.0.2 on 2026-03-23 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documenttemplate_generateddocument_templatefield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты (База знаний)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено администратором'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Введённые данные'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Создан / Ожидает'), ('generated', 'Сгенерирован'), ('approved', 'Одобрен администратором'), ('error', 'Ошибка генерации')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='key',
            field=models.CharField(help_text='Например: client_fio', max_length=50, verbose_name='Ключ (как в docx)'),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('options', models.JSONField(default=list, help_text='Список строк: ["Вариант 1", "Вариант 2", ...]', verbose_name='Варианты ответов')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='Индекс правильного ответа (с 0)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.knowledgetest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
    ]
