# Generated by Django 6.0.2 on 2026-03-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_expense_updated_at_financialperiod_updated_at_and_more'),
        ('documents', '0006_knowledgetest_generateddocument_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='analytics.deal', verbose_name='Сделка'),
        ),
    ]
