# Generated by Django 6.0.2 on 2026-04-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_generateddocument_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=20, verbose_name='Статус рассмотрения')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('approved_file', models.FileField(blank=True, null=True, upload_to='generated_documents/approved/', verbose_name='Одобренный файл')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='documents.generateddocument', verbose_name='Документ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рассмотрение документа',
                'verbose_name_plural': 'Рассмотрения документов',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Ответы пользователя')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Завершено')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='documents.knowledgetest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
    ]
