# Generated by Django 6.0.2 on 2026-05-20 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_repair_missing_0008_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosnippet',
            options={'ordering': ['section__order', 'category', 'order', 'title'], 'verbose_name': 'База знаний', 'verbose_name_plural': 'База знаний'},
        ),
        migrations.AddField(
            model_name='infosnippet',
            name='content_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain', 'Обычный текст'), ('html', 'HTML')], default='markdown', max_length=20, verbose_name='Формат текста'),
        ),
        migrations.AlterField(
            model_name='infosnippet',
            name='category',
            field=models.CharField(choices=[('script', 'Скрипты продаж'), ('faq', 'Ответы на частые вопросы'), ('requisites', 'Реквизиты и Счета'), ('links', 'Полезные ссылки')], default='faq', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='infosnippet',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание раздела / Markdown')),
                ('icon', models.CharField(blank=True, default='folder', max_length=60, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Цвет')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='knowledge_sections/images/', verbose_name='Фото / обложка раздела')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_sections/files/', verbose_name='Файл раздела')),
                ('external_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Ссылка раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_sections', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.knowledgesection', verbose_name='Родительский раздел')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='responsible_knowledge_sections', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные сотрудники')),
            ],
            options={
                'verbose_name': 'Раздел базы знаний',
                'verbose_name_plural': 'Разделы базы знаний',
                'ordering': ['parent__id', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='infosnippet',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='documents.knowledgesection', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='knowledgetest',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='documents.knowledgesection', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='KnowledgeSectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('attachment_type', models.CharField(choices=[('file', 'Файл'), ('image', 'Фото'), ('link', 'Ссылка')], default='file', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_sections/attachments/', verbose_name='Файл / фото')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Ссылка')),
                ('note', models.TextField(blank=True, default='', verbose_name='Описание / комментарий')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.knowledgesection', verbose_name='Раздел базы знаний')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_section_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Файл/ссылка раздела базы знаний',
                'verbose_name_plural': 'Файлы и ссылки разделов базы знаний',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
