# Generated manually for ERP rebuild Sprint 2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название источника')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Код источника')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={'verbose_name': 'Источник лида', 'verbose_name_plural': 'Источники лидов', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / Имя')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('direction', models.CharField(blank=True, choices=[('admission', 'Поступление'), ('visa', 'Виза'), ('translation', 'Переводы'), ('tickets', 'Билеты'), ('work_visa', 'Рабочие визы'), ('other', 'Другое')], max_length=50, verbose_name='Направление')),
                ('interested_country', models.CharField(blank=True, max_length=100, verbose_name='Интересующая страна обучения')),
                ('interested_program', models.CharField(blank=True, max_length=255, verbose_name='Интересующая программа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('qualified', 'Квалифицирован'), ('converted', 'Стал клиентом'), ('lost', 'Потерян'), ('spam', 'Спам')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('submitter_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP отправителя')),
                ('submitter_user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('submitter_referer', models.URLField(blank=True, default='', max_length=1000, verbose_name='Referer')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конвертации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_leads', to='organizations.company', verbose_name='Компания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='organizations.office', verbose_name='Офис')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource', verbose_name='Источник')),
            ],
            options={'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО клиента')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=100, verbose_name='Гражданство')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('address_registration', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('passport_local_num', models.CharField(blank=True, max_length=50, verbose_name='Внутренний паспорт')),
                ('passport_inter_num', models.CharField(blank=True, max_length=50, verbose_name='Загранпаспорт')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('consultation', 'Консультация'), ('documents', 'Сбор документов'), ('application', 'Подача заявки'), ('invitation', 'Приглашение'), ('visa', 'Виза'), ('arrived', 'Прибыл'), ('success', 'Завершён успешно'), ('rejected', 'Отказ'), ('archive', 'Архив')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Приоритетный клиент')),
                ('is_partner_client', models.BooleanField(default=False, verbose_name='Клиент от партнёра')),
                ('partner_name', models.CharField(blank=True, max_length=255, verbose_name='Партнёр')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_clients', to='organizations.company', verbose_name='Компания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_clients', to=settings.AUTH_USER_MODEL, verbose_name='Основной менеджер')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_clients', to='organizations.office', verbose_name='Офис')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_crm_clients', to=settings.AUTH_USER_MODEL, verbose_name='Доступ открыт также для')),
                ('source_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='crm.lead', verbose_name='Исходный лид')),
            ],
            options={'verbose_name': 'Клиент CRM', 'verbose_name_plural': 'Клиенты CRM', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('university_name', models.CharField(blank=True, max_length=255, verbose_name='ВУЗ')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='Программа')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна обучения')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Степень')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Язык обучения')),
                ('intake', models.CharField(blank=True, max_length=100, verbose_name='Набор / intake')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('documents', 'Сбор документов'), ('submitted', 'Подано'), ('in_review', 'На рассмотрении'), ('accepted', 'Принято'), ('invitation', 'Приглашение получено'), ('visa', 'Виза'), ('enrolled', 'Зачислен'), ('rejected', 'Отказ'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=32, verbose_name='Статус заявки')),
                ('submitted_at', models.DateField(blank=True, null=True, verbose_name='Дата подачи')),
                ('decision_at', models.DateField(blank=True, null=True, verbose_name='Дата решения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_applications', to='organizations.company', verbose_name='Компания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_applications', to='organizations.office', verbose_name='Офис')),
            ],
            options={'verbose_name': 'Заявка на поступление', 'verbose_name_plural': 'Заявки на поступление', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('activity_type', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('meeting', 'Встреча'), ('note', 'Заметка'), ('status_change', 'Смена статуса'), ('document', 'Документ'), ('payment', 'Платёж')], default='note', max_length=32, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок / напоминание')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={'verbose_name': 'Активность клиента', 'verbose_name_plural': 'Активности клиентов', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватная заметка')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.client', verbose_name='Клиент')),
            ],
            options={'verbose_name': 'Заметка клиента', 'verbose_name_plural': 'Заметки клиентов', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='erp/crm/client_files/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Тип файла')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.application', verbose_name='Заявка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.client', verbose_name='Клиент')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_files', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={'verbose_name': 'Файл клиента', 'verbose_name_plural': 'Файлы клиентов', 'ordering': ['-created_at']},
        ),
    ]
