# Generated by Django 6.0.2 on 2026-05-20 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company', 'office', 'status'], name='crm_applica_company_585004_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['manager', 'status'], name='crm_applica_manager_6c0bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client', 'status'], name='crm_applica_client__7f0108_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'office', 'status'], name='crm_client_company_d0fb52_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['manager', 'status'], name='crm_client_manager_ff9239_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='crm_client_phone_7f59d5_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='crm_client_full_na_3f948f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'office', 'status'], name='crm_lead_company_ffc8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['manager', 'status'], name='crm_lead_manager_709c67_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='crm_lead_phone_8180e8_idx'),
        ),
    ]
