# Generated by Django 6.0.2 on 2026-05-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_application_crm_applica_company_585004_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текущее образование'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_school',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текущий вуз / школа'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_study_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна текущего обучения'),
        ),
        migrations.AddField(
            model_name='client',
            name='direction',
            field=models.CharField(blank=True, choices=[('admission', 'Поступление'), ('visa', 'Виза'), ('translation', 'Переводы'), ('tickets', 'Билеты'), ('work_visa', 'Рабочие визы'), ('other', 'Другое')], max_length=50, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_education_doc',
            field=models.BooleanField(default=False, verbose_name='Есть аттестат / диплом'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name='Есть паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_photo',
            field=models.BooleanField(default=False, verbose_name='Есть фото'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_translation',
            field=models.BooleanField(default=False, verbose_name='Есть перевод'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Интересующая страна'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_program',
            field=models.CharField(blank=True, max_length=255, verbose_name='Интересующая программа'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_university',
            field=models.CharField(blank=True, max_length=255, verbose_name='Интересующий вуз'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_clients', to='crm.leadsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='relative_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО родственника'),
        ),
        migrations.AddField(
            model_name='client',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=80, verbose_name='Телефон родственника'),
        ),
        migrations.AddField(
            model_name='client',
            name='relative_relation',
            field=models.CharField(blank=True, max_length=120, verbose_name='Кем приходится'),
        ),
        migrations.AddField(
            model_name='client',
            name='relative_workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы родственника'),
        ),
    ]
