# Generated by Django 6.0.2 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_current_education_client_current_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
    ]
