# Generated by Django 6.0.2 on 2026-05-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_custom_data'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='api_source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='API source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивации'),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Кто архивировал'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitter_origin',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='lead',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата взятия ответственности'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'status'], name='crm_lead_is_arch_f75f5b_idx'),
        ),
    ]
