# Generated by Django 6.0.2 on 2026-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_clientfile_external_review_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientquestionnaire',
            new_name='crm_clientq_status_607b66_idx',
            old_name='crm_clientq_status_7a6a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='clientquestionnaire',
            new_name='crm_clientq_externa_ee6703_idx',
            old_name='crm_clientq_externa_0d0c67_idx',
        ),
        migrations.AlterField(
            model_name='clientquestionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='clientquestionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
