# Generated by Django 6.0.2 on 2026-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_crm_clientq_status_7a6a3f_idx_crm_clientq_status_607b66_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='academic_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Год поступления'),
        ),
        migrations.AddField(
            model_name='client',
            name='sl_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='SL-ID'),
        ),
    ]
