# Generated by Django 5.1.7 on 2026-09-06 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_canonical_identity_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_result',
            field=models.CharField(blank=True, max_length=80, verbose_name='Результат поступления'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.CharField(choices=[('LEAD', 'Лид'), ('CLIENT_CREATED', 'Клиент создан'), ('DOCUMENT_COLLECTION', 'Сбор документов'), ('DOCUMENTS_READY', 'Документы готовы'), ('APPLICATION_PREPARATION', 'Подготовка заявки'), ('APPLICATION_SUBMITTED', 'Заявка подана'), ('UNIVERSITY_REVIEW', 'Рассмотрение вузом'), ('EXAM_REQUIRED', 'Требуется экзамен'), ('EXAM_SCHEDULED', 'Экзамен назначен'), ('EXAM_COMPLETED', 'Экзамен пройден'), ('WAITING_RESULT', 'Ожидание результата'), ('EXAM_PASSED', 'Экзамен сдан'), ('EXAM_FAILED', 'Экзамен не сдан'), ('CONTRACT_WAITING', 'Ожидание договора вуза'), ('CONTRACT_RECEIVED', 'Договор вуза получен'), ('UNIVERSITY_PAYMENT_WAITING', 'Ожидание оплаты вузу'), ('UNIVERSITY_PAYMENT_CONFIRMED', 'Оплата вузу подтверждена'), ('ADMISSION_CONFIRMED', 'Поступление подтверждено'), ('ORDER_WAITING', 'Ожидание приказа'), ('INVITATION_WAITING', 'Ожидание приглашения'), ('INVITATION_RECEIVED', 'Приглашение получено'), ('VISA_PREPARATION', 'Подготовка визы'), ('VISA_APPLIED', 'Документы на визу поданы'), ('VISA_RECEIVED', 'Виза получена'), ('ARRIVAL_PLANNED', 'Прибытие запланировано'), ('ENROLLED', 'Зачислен'), ('REJECTED', 'Отказ'), ('CANCELLED', 'Отменено'), ('ON_HOLD', 'Приостановлено')], db_index=True, default='DOCUMENT_COLLECTION', max_length=40, verbose_name='Этап поступления'),
        ),
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='application',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('government', 'Государственная линия'), ('budget', 'Бюджет'), ('contract', 'Контракт'), ('medical', 'Медик')], max_length=20, verbose_name='Форма поступления'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service', models.CharField(db_index=True, default='manager_sl', max_length=80)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_activity_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_activity', to='crm.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_activity', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['student', 'created_at'], name='crm_activit_student_e9ba5e_idx'), models.Index(fields=['application', 'created_at'], name='crm_activit_applica_5d00ae_idx'), models.Index(fields=['action', 'created_at'], name='crm_activit_action_9b2866_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('old_stage', models.CharField(blank=True, choices=[('LEAD', 'Лид'), ('CLIENT_CREATED', 'Клиент создан'), ('DOCUMENT_COLLECTION', 'Сбор документов'), ('DOCUMENTS_READY', 'Документы готовы'), ('APPLICATION_PREPARATION', 'Подготовка заявки'), ('APPLICATION_SUBMITTED', 'Заявка подана'), ('UNIVERSITY_REVIEW', 'Рассмотрение вузом'), ('EXAM_REQUIRED', 'Требуется экзамен'), ('EXAM_SCHEDULED', 'Экзамен назначен'), ('EXAM_COMPLETED', 'Экзамен пройден'), ('WAITING_RESULT', 'Ожидание результата'), ('EXAM_PASSED', 'Экзамен сдан'), ('EXAM_FAILED', 'Экзамен не сдан'), ('CONTRACT_WAITING', 'Ожидание договора вуза'), ('CONTRACT_RECEIVED', 'Договор вуза получен'), ('UNIVERSITY_PAYMENT_WAITING', 'Ожидание оплаты вузу'), ('UNIVERSITY_PAYMENT_CONFIRMED', 'Оплата вузу подтверждена'), ('ADMISSION_CONFIRMED', 'Поступление подтверждено'), ('ORDER_WAITING', 'Ожидание приказа'), ('INVITATION_WAITING', 'Ожидание приглашения'), ('INVITATION_RECEIVED', 'Приглашение получено'), ('VISA_PREPARATION', 'Подготовка визы'), ('VISA_APPLIED', 'Документы на визу поданы'), ('VISA_RECEIVED', 'Виза получена'), ('ARRIVAL_PLANNED', 'Прибытие запланировано'), ('ENROLLED', 'Зачислен'), ('REJECTED', 'Отказ'), ('CANCELLED', 'Отменено'), ('ON_HOLD', 'Приостановлено')], max_length=40)),
                ('new_stage', models.CharField(choices=[('LEAD', 'Лид'), ('CLIENT_CREATED', 'Клиент создан'), ('DOCUMENT_COLLECTION', 'Сбор документов'), ('DOCUMENTS_READY', 'Документы готовы'), ('APPLICATION_PREPARATION', 'Подготовка заявки'), ('APPLICATION_SUBMITTED', 'Заявка подана'), ('UNIVERSITY_REVIEW', 'Рассмотрение вузом'), ('EXAM_REQUIRED', 'Требуется экзамен'), ('EXAM_SCHEDULED', 'Экзамен назначен'), ('EXAM_COMPLETED', 'Экзамен пройден'), ('WAITING_RESULT', 'Ожидание результата'), ('EXAM_PASSED', 'Экзамен сдан'), ('EXAM_FAILED', 'Экзамен не сдан'), ('CONTRACT_WAITING', 'Ожидание договора вуза'), ('CONTRACT_RECEIVED', 'Договор вуза получен'), ('UNIVERSITY_PAYMENT_WAITING', 'Ожидание оплаты вузу'), ('UNIVERSITY_PAYMENT_CONFIRMED', 'Оплата вузу подтверждена'), ('ADMISSION_CONFIRMED', 'Поступление подтверждено'), ('ORDER_WAITING', 'Ожидание приказа'), ('INVITATION_WAITING', 'Ожидание приглашения'), ('INVITATION_RECEIVED', 'Приглашение получено'), ('VISA_PREPARATION', 'Подготовка визы'), ('VISA_APPLIED', 'Документы на визу поданы'), ('VISA_RECEIVED', 'Виза получена'), ('ARRIVAL_PLANNED', 'Прибытие запланировано'), ('ENROLLED', 'Зачислен'), ('REJECTED', 'Отказ'), ('CANCELLED', 'Отменено'), ('ON_HOLD', 'Приостановлено')], max_length=40)),
                ('source_service', models.CharField(default='manager_sl', max_length=80)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_stage_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_history', to='crm.application')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['application', 'created_at'], name='crm_applica_applica_94fae7_idx')],
            },
        ),
    ]
