# Generated by Django 5.1.7 on 2026-09-07 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_admission_workflow_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system', models.CharField(choices=[('RUID', 'RUID'), ('UNIVERSITY_PORTAL', 'Личный кабинет университета'), ('GOVERNMENT_PORTAL', 'Государственный портал'), ('EMAIL', 'Почтовый аккаунт'), ('OTHER', 'Другая система')], db_index=True, max_length=40, verbose_name='Система')),
                ('provider_name', models.CharField(max_length=255, verbose_name='Название портала / вуза')),
                ('portal_url', models.URLField(blank=True, verbose_name='Адрес входа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email аккаунта')),
                ('login', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('secret_ciphertext', models.TextField(blank=True, editable=False, verbose_name='Зашифрованные данные доступа')),
                ('secret_updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Пароль обновлён')),
                ('status', models.CharField(choices=[('PLANNED', 'Нужно создать'), ('CREATED', 'Создан'), ('PENDING_VERIFICATION', 'Ожидает подтверждения'), ('VERIFIED', 'Подтверждён'), ('BLOCKED', 'Заблокирован'), ('ERROR', 'Проблема'), ('ARCHIVED', 'Архив')], db_index=True, default='PLANNED', max_length=32, verbose_name='Статус')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('issue', models.CharField(blank=True, max_length=1000, verbose_name='Проблема')),
                ('notes', models.CharField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_accounts', to='crm.application', verbose_name='Заявка в университет')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_external_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_accounts', to='crm.client', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Внешний аккаунт студента',
                'verbose_name_plural': 'Внешние аккаунты студентов',
                'ordering': ['-created_at'],
                'permissions': [('view_externalaccount_secret', 'Может просматривать пароль внешнего аккаунта')],
                'indexes': [models.Index(fields=['student', 'status'], name='crm_externa_student_e6689d_idx'), models.Index(fields=['application', 'status'], name='crm_externa_applica_8ddacd_idx'), models.Index(fields=['system', 'status'], name='crm_externa_system_0c72c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'application', 'system', 'provider_name'), name='crm_unique_external_account', nulls_distinct=False)],
            },
        ),
    ]
