# Generated by Django 5.1.7 on 2026-09-08 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_externalaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFileReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('reviewer_data', models.JSONField(blank=True, default=dict)),
                ('source_service', models.CharField(db_index=True, default='manager_sl', max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ClientFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1000)),
                ('folder_url', models.URLField(blank=True, max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('source_service', models.CharField(db_index=True, default='manager_sl', max_length=80)),
                ('uploader_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-version_number'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddField(
            model_name='clientfile',
            name='current_version_number',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Текущая версия'),
        ),
        migrations.AddConstraint(
            model_name='clientfile',
            constraint=models.UniqueConstraint(condition=models.Q(('external_mobile_document_id__isnull', False)), fields=('source', 'external_mobile_document_id'), name='unique_external_mobile_document_per_source'),
        ),
        migrations.AddField(
            model_name='clientfilereviewevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='crm.clientfile'),
        ),
        migrations.AddField(
            model_name='clientfilereviewevent',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_file_review_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfileversion',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to='crm.application'),
        ),
        migrations.AddField(
            model_name='clientfileversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crm.clientfile'),
        ),
        migrations.AddField(
            model_name='clientfileversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_file_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfilereviewevent',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='crm.clientfileversion'),
        ),
        migrations.AddIndex(
            model_name='clientfileversion',
            index=models.Index(fields=['document', 'version_number'], name='crm_clientf_documen_9d5cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfileversion',
            index=models.Index(fields=['application', 'created_at'], name='crm_clientf_applica_34c99f_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientfileversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_client_file_version'),
        ),
        migrations.AddIndex(
            model_name='clientfilereviewevent',
            index=models.Index(fields=['document', 'created_at'], name='crm_clientf_documen_d8f9db_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfilereviewevent',
            index=models.Index(fields=['version', 'created_at'], name='crm_clientf_version_fa8032_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfilereviewevent',
            index=models.Index(fields=['status', 'created_at'], name='crm_clientf_status_0e4cb2_idx'),
        ),
    ]
