# Generated by Django 5.1.7 on 2026-09-11 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_applicationexam_applicationexamevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('source_language', models.CharField(default='tk', max_length=16, verbose_name='Исходный язык')),
                ('target_language', models.CharField(default='ru', max_length=16, verbose_name='Язык перевода')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='Шаблон')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('UPLOADED', 'Загружен'), ('PROCESSING', 'Обрабатывается'), ('REVIEW', 'На проверке'), ('READY', 'Готов'), ('ERROR', 'Ошибка')], db_index=True, default='UPLOADED', max_length=20)),
                ('source_storage_path', models.CharField(blank=True, max_length=1000)),
                ('result_storage_path', models.CharField(blank=True, max_length=1000)),
                ('source_service', models.CharField(default='translate_sl', max_length=80)),
                ('source_id', models.CharField(max_length=120)),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='crm.application', verbose_name='Заявка в университет')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_translations', to=settings.AUTH_USER_MODEL)),
                ('source_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='crm.clientfileversion', verbose_name='Исходная версия документа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='crm.client', verbose_name='Студент')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('source_service', models.CharField(default='translate_sl', max_length=80)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_events', to=settings.AUTH_USER_MODEL)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='crm.translationrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='translationrecord',
            index=models.Index(fields=['student', 'status'], name='crm_transla_student_324a69_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrecord',
            index=models.Index(fields=['application', 'created_at'], name='crm_transla_applica_4bdbf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='translationrecord',
            constraint=models.UniqueConstraint(fields=('source_service', 'source_id'), name='unique_translation_source_record'),
        ),
        migrations.AddIndex(
            model_name='translationevent',
            index=models.Index(fields=['translation', 'created_at'], name='crm_transla_transla_e72f6d_idx'),
        ),
    ]
