# Generated by Django 5.1.7 on 2026-09-12 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_translationrecord_translationevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_service', models.CharField(default='smtp_sl', max_length=80)),
                ('source_id', models.CharField(max_length=160)),
                ('mailbox', models.EmailField(max_length=254, verbose_name='Почтовый ящик')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='Получено')),
                ('category', models.CharField(choices=[('primary', 'Основные'), ('google', 'Уведомления Google'), ('spam', 'Спам'), ('sent', 'Отправленные')], db_index=True, default='primary', max_length=20)),
                ('importance', models.CharField(choices=[('normal', 'Обычное'), ('important', 'Важное'), ('urgent', 'Срочное')], db_index=True, default='normal', max_length=20)),
                ('university_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Вуз')),
                ('attachment_count', models.PositiveSmallIntegerField(default=0)),
                ('body_preview', models.CharField(blank=True, max_length=1000, verbose_name='Фрагмент письма')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='Открыть в почтовом сервисе')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Обработано')),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_records', to='crm.application', verbose_name='Заявка в университет')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_email_records', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_records', to='crm.client', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Письмо студента',
                'verbose_name_plural': 'Письма студентов',
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['student', 'received_at'], name='crm_emailre_student_db630c_idx'), models.Index(fields=['application', 'received_at'], name='crm_emailre_applica_10ed90_idx'), models.Index(fields=['responsible', 'processed', 'received_at'], name='crm_emailre_respons_10ebc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_service', 'source_id'), name='unique_email_source_record')],
            },
        ),
    ]
