# Generated by Django 6.0.2 on 2026-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-is_pinned', '-updated_at'), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплена'),
        ),
    ]
