# Generated by Django 6.0.2 on 2026-05-20 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_task_is_pinned'),
        ('users', '0007_officetarget_useraccessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание / Markdown')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Город')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('paused', 'Пауза'), ('done', 'Завершён'), ('archived', 'Архив')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн проекта')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='Скрыт админом')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.office', verbose_name='Офис')),
                ('participants', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Участники с доступом')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('attachment_type', models.CharField(choices=[('file', 'Файл'), ('image', 'Фото'), ('link', 'Ссылка')], default='file', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_attachments/', verbose_name='Файл/Фото')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Ссылка')),
                ('note', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.project', verbose_name='Проект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Файл/ссылка проекта',
                'verbose_name_plural': 'Файлы и ссылки проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание раздела')),
                ('color', models.CharField(blank=True, default='', max_length=32, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_sections', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал раздел')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tasks.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Раздел проекта',
                'verbose_name_plural': 'Разделы проектов',
                'ordering': ['-is_pinned', 'order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок записи')),
                ('body', models.TextField(blank=True, default='', verbose_name='Информация / текст поста')),
                ('copy_text', models.TextField(blank=True, default='', verbose_name='Текст для копирования')),
                ('note', models.TextField(blank=True, default='', verbose_name='Внутренняя заметка')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_section_posts', to=settings.AUTH_USER_MODEL, verbose_name='Кто заполнил')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tasks.projectsection', verbose_name='Раздел')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_section_posts', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Запись раздела проекта',
                'verbose_name_plural': 'Записи разделов проектов',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание / Markdown')),
                ('status', models.CharField(choices=[('todo', 'Нужно сделать'), ('process', 'В работе'), ('review', 'На проверке'), ('done', 'Готово')], db_index=True, default='todo', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.projecttask', verbose_name='Родительская задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача проекта',
                'verbose_name_plural': 'Задачи проектов',
                'ordering': ['parent_id', 'status', 'order', '-updated_at'],
            },
        ),
    ]
