# Generated by Django 6.0.2 on 2026-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты (ISO)')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('symbol', models.CharField(default='$', max_length=5, verbose_name='Символ')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Сколько единиц этой валюты в 1 долларе?', max_digits=10, verbose_name='Курс к 1 USD')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('degree', models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('language', 'Языковые курсы')], max_length=100, verbose_name='Степень')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость обучения (Местная валюта)')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость НАШИХ услуг (USD)')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена (Архив)')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВУЗа')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, upload_to='uni_logos/', verbose_name='Логотип')),
                ('description', models.TextField(verbose_name='Общее описание')),
                ('expenses_info', models.TextField(blank=True, verbose_name='Расходы (проживание и т.д.)')),
                ('invitation_info', models.TextField(blank=True, verbose_name='Информация о приглашении')),
                ('intake_period', models.CharField(help_text='Например: Сентябрь - Январь', max_length=100, verbose_name='Период приема')),
                ('age_limit', models.CharField(blank=True, max_length=50, verbose_name='Возрастные ограничения')),
                ('required_docs', models.TextField(verbose_name='Нужные документы')),
                ('contacts', models.TextField(verbose_name='Контакты университета')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
    ]
