# Generated by Django 6.0.2 on 2026-02-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('specialist', 'Специалитет'), ('language', 'Языковые курсы')], max_length=100, verbose_name='Степень'),
        ),
    ]
