# Generated by Django 6.0.2 on 2026-02-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_program_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['university__name', 'name'], 'verbose_name': 'Программа обучения', 'verbose_name_plural': 'Программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AlterField(
            model_name='program',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость НАШИХ услуг (USD)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='catalog.university', verbose_name='Университет'),
        ),
    ]
