# Generated by Django 6.0.2 on 2026-02-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_currency_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='service_fee',
        ),
    ]
