# Generated by Django 6.0.2 on 2026-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_program_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость НАШИХ услуг (USD)'),
        ),
    ]
