# Generated by Django 6.0.2 on 2026-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_program_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
