# Generated by Django 6.0.2 on 2026-08-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_currency_updated_at_program_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название программы'),
        ),
    ]
