# Generated by Django 6.0.2 on 2026-05-22 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('started', 'Started'), ('report_submitted', 'Report submitted'), ('closed', 'Closed'), ('auto_closed', 'Auto closed'), ('missed', 'Missed')], db_index=True, default='not_started', max_length=32, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('auto_closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Auto closed at')),
                ('total_work_seconds', models.PositiveIntegerField(default=0, verbose_name='Total work seconds')),
                ('report_required', models.BooleanField(default=True, verbose_name='Report required')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_workdays', to='organizations.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_workdays', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workdays', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Work day',
                'verbose_name_plural': 'Work days',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('content', models.TextField(verbose_name='Content')),
                ('results', models.TextField(blank=True, verbose_name='Results')),
                ('plans', models.TextField(blank=True, verbose_name='Plans')),
                ('problems', models.TextField(blank=True, verbose_name='Problems')),
                ('leads_processed', models.PositiveIntegerField(default=0, verbose_name='Leads processed')),
                ('deals_closed', models.PositiveIntegerField(default=0, verbose_name='Deals closed')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_reports', to='organizations.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_reports', to='organizations.office', verbose_name='Office')),
                ('workday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='attendance.workday', verbose_name='Work day')),
            ],
            options={
                'verbose_name': 'Daily report',
                'verbose_name_plural': 'Daily reports',
                'ordering': ['-date', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoCloseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('previous_status', models.CharField(blank=True, max_length=32, verbose_name='Previous status')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_auto_close_logs', to='organizations.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_auto_close_logs', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_auto_close_logs', to='organizations.office', verbose_name='Office')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_close_logs', to='attendance.workday', verbose_name='Work day')),
            ],
            options={
                'verbose_name': 'Auto close log',
                'verbose_name_plural': 'Auto close logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration seconds')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('start_note', models.TextField(blank=True, verbose_name='Start note')),
                ('end_note', models.TextField(blank=True, verbose_name='End note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.workday', verbose_name='Work day')),
            ],
            options={
                'verbose_name': 'Work session',
                'verbose_name_plural': 'Work sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('reminder_type', models.CharField(choices=[('start_workday', 'Start workday'), ('daily_report', 'Daily report'), ('close_workday', 'Close workday')], db_index=True, max_length=32, verbose_name='Reminder type')),
                ('scheduled_time', models.TimeField(verbose_name='Scheduled time')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='Weekdays')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminders', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminders', to='organizations.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Attendance reminder',
                'verbose_name_plural': 'Attendance reminders',
                'ordering': ['company__name', 'scheduled_time'],
                'indexes': [models.Index(fields=['company', 'office', 'reminder_type', 'is_active'], name='attendance__company_49e4ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['company', 'office', 'status'], name='attendance__company_b32b41_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_10fbab_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['date', 'status'], name='attendance__date_31fe48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('company', 'employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['company', 'office', 'date'], name='attendance__company_e5f391_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_d371ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('company', 'employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='autocloselog',
            index=models.Index(fields=['company', 'office', 'created_at'], name='attendance__company_5d8469_idx'),
        ),
        migrations.AddIndex(
            model_name='autocloselog',
            index=models.Index(fields=['employee', 'created_at'], name='attendance__employe_941e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['employee', 'is_active'], name='attendance__employe_e4dc86_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['workday', 'is_active'], name='attendance__workday_dfa589_idx'),
        ),
    ]
