# Generated by Django 5.1.7 on 2026-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('started', 'Рабочий день идёт'), ('report_submitted', 'Отчёт отправлен'), ('closed', 'Закрыт сотрудником'), ('auto_closed', 'Закрыт автоматически'), ('missed', 'Не вышел на работу')], db_index=True, default='not_started', max_length=32, verbose_name='Status'),
        ),
    ]
