# Generated by Django 5.1.7 on 2026-09-23 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancetelegramdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetelegramdelivery',
            name='target_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Получатель Telegram'),
        ),
        migrations.AlterField(
            model_name='attendancetelegramdelivery',
            name='event_type',
            field=models.CharField(choices=[('arrival', 'Приход'), ('departure', 'Уход'), ('auto_close', 'Автоматическое закрытие'), ('missed', 'Неявка'), ('weekly_summary', 'Недельный отчёт'), ('start_reminder', 'Напоминание о начале дня'), ('close_reminder', 'Напоминание о завершении дня')], db_index=True, max_length=32, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='EmployeeTelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Фамилия в Telegram')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Подключён')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_telegram_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram сотрудника',
                'verbose_name_plural': 'Telegram сотрудников',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш кода')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_telegram_link_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код подключения Telegram',
                'verbose_name_plural': 'Коды подключения Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
