# Generated by Django 6.0.2 on 2026-05-20 10:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Страна')),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='Код страны')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='erp/education/flags/', verbose_name='Флаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна обучения',
                'verbose_name_plural': 'Страны обучения',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=80, verbose_name='Название валюты')),
                ('symbol', models.CharField(default='$', max_length=8, verbose_name='Символ')),
                ('rate_to_usd', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='Курс к USD')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название программы')),
                ('degree', models.CharField(choices=[('school', 'Школа'), ('foundation', 'Foundation / подготовительный курс'), ('language', 'Языковые курсы'), ('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура'), ('phd', 'PhD / аспирантура'), ('other', 'Другое')], db_index=True, default='bachelor', max_length=32, verbose_name='Степень')),
                ('faculty', models.CharField(blank=True, max_length=255, verbose_name='Факультет')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Язык обучения')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Архив')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['university__name', 'degree', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=120, verbose_name='Город')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='education.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город обучения',
                'verbose_name_plural': 'Города обучения',
                'ordering': ['country__name', 'sort_order', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=150, verbose_name='Название набора')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн подачи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='education.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Набор / intake',
                'verbose_name_plural': 'Наборы / intakes',
                'ordering': ['program__university__name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Стоимость обучения')),
                ('service_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Стоимость услуг компании USD')),
                ('application_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Application fee')),
                ('dormitory_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общежитие')),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Страховка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_fees', to='education.currency', verbose_name='Валюта')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='education.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Стоимость программы',
                'verbose_name_plural': 'Стоимость программ',
                'ordering': ['program__university__name', 'program__name', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название ВУЗа')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Юридическое название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='erp/education/university_logos/', verbose_name='Логотип')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='erp/education/university_covers/', verbose_name='Главное изображение')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='Условия поступления')),
                ('invitation_info', models.TextField(blank=True, verbose_name='Условия приглашения')),
                ('dormitory_info', models.TextField(blank=True, verbose_name='Общежитие')),
                ('expenses_info', models.TextField(blank=True, verbose_name='Расходы и проживание')),
                ('age_limit', models.CharField(blank=True, max_length=100, verbose_name='Возрастные ограничения')),
                ('commission_info', models.TextField(blank=True, verbose_name='Партнёрские условия / комиссия')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_universities_added', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='education.city', verbose_name='Город')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_universities', to='organizations.company', verbose_name='Компания')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='education.country', verbose_name='Страна')),
                ('local_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='education.currency', verbose_name='Валюта страны')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗы',
                'ordering': ['country__name', 'city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='education.program', verbose_name='Программа')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='education.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Требуемый документ',
                'verbose_name_plural': 'Требуемые документы',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education.university', verbose_name='ВУЗ'),
        ),
        migrations.CreateModel(
            name='UniversityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=120, verbose_name='Мессенджер')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_people', to='education.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Контакт ВУЗа',
                'verbose_name_plural': 'Контакты ВУЗов',
                'ordering': ['university__name', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country', 'city', 'is_active'], name='education_u_country_0e740a_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='education_u_name_d1fc60_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['university', 'degree', 'is_active'], name='education_p_univers_588766_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='education_p_name_3c0bd5_idx'),
        ),
    ]
