# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_programfee_valid_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/education/country_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/education/country_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='city',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/education/city_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/education/city_images/', verbose_name='Изображение'),
        ),
    ]
