# Generated by Django 6.0.2 on 2026-08-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_country_city_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Код валюты'),
        ),
    ]
