# Generated by Django 6.0.2 on 2026-05-22 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('token', models.TextField(unique=True, verbose_name='Device token')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='Platform')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device name')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='App version')),
                ('locale', models.CharField(blank=True, max_length=32, verbose_name='Locale')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='Timezone')),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last seen at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_device_tokens', to='organizations.company', verbose_name='Company')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_device_tokens', to='organizations.office', verbose_name='Office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'ERP device token',
                'verbose_name_plural': 'ERP device tokens',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance'), ('task', 'Task'), ('document', 'Document'), ('payment', 'Payment'), ('system', 'System'), ('knowledge', 'Knowledge')], db_index=True, default='system', max_length=32, verbose_name='Notification type')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push'), ('email', 'Email')], db_index=True, default='in_app', max_length=32, verbose_name='Channel')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=32, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=32, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='Target URL')),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Related object id')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Queued at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed at')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_notifications', to='organizations.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Related content type')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_notifications', to='organizations.office', verbose_name='Office')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'ERP notification',
                'verbose_name_plural': 'ERP notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push'), ('email', 'Email')], db_index=True, max_length=32, verbose_name='Channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=32, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=64, verbose_name='Provider')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Recipient')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Request data')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('device_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='erp_notifications.devicetoken', verbose_name='Device token')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='erp_notifications.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'ERP notification log',
                'verbose_name_plural': 'ERP notification logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('code', models.SlugField(max_length=100, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance'), ('task', 'Task'), ('document', 'Document'), ('payment', 'Payment'), ('system', 'System'), ('knowledge', 'Knowledge')], db_index=True, default='system', max_length=32, verbose_name='Notification type')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push'), ('email', 'Email')], db_index=True, default='in_app', max_length=32, verbose_name='Default channel')),
                ('title_template', models.CharField(max_length=255, verbose_name='Title template')),
                ('body_template', models.TextField(blank=True, verbose_name='Body template')),
                ('data_template', models.JSONField(blank=True, default=dict, verbose_name='Data template')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='Send in-app')),
                ('send_push', models.BooleanField(default=True, verbose_name='Send push')),
                ('send_email', models.BooleanField(default=False, verbose_name='Send email')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_notification_templates', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_notification_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'ERP notification template',
                'verbose_name_plural': 'ERP notification templates',
                'ordering': ['company__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='erp_notifications.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['company', 'office', 'is_active'], name='erp_notific_company_3116c5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='erp_notific_user_id_585c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform', 'is_active'], name='erp_notific_platfor_ad9862_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'channel'], name='erp_notific_notific_6b15f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['device_token', 'created_at'], name='erp_notific_device__f5a326_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='erp_notific_status_f5327f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['company', 'is_active'], name='erp_notific_company_ed4527_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['notification_type', 'channel'], name='erp_notific_notific_fa991c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['code'], name='erp_notific_code_41a2e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'office', 'status'], name='erp_notific_company_a2c25f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='erp_notific_recipie_7899a6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='erp_notific_notific_174a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='erp_notific_content_cb2363_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='erp_notific_created_100a81_idx'),
        ),
    ]
