# Generated by Django 6.0.2 on 2026-05-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('erp_notifications', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешно'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], db_index=True, default='info', max_length=32, verbose_name='Тип уведомления')),
                ('target_type', models.CharField(choices=[('user', 'Один сотрудник'), ('office', 'Офис'), ('all', 'Все сотрудники')], db_index=True, default='user', max_length=32, verbose_name='Кому отправлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('cancelled', 'Отменено')], db_index=True, default='sent', max_length=32, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to='organizations.company', verbose_name='Компания')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches', to='organizations.office', verbose_name='Офис отправителя')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches_sent', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил')),
                ('target_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches_received', to='organizations.office', verbose_name='Офис получателей')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches_received_directly', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Рассылка уведомлений',
                'verbose_name_plural': 'Рассылки уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='erp_notifications.notificationbatch', verbose_name='Рассылка'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['batch', 'status'], name='erp_notific_batch_i_bb8099_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['company', 'office', 'status'], name='erp_notific_company_43cc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['sender', 'created_at'], name='erp_notific_sender__e001dd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['target_type', 'created_at'], name='erp_notific_target__51c8ae_idx'),
        ),
    ]
