from django.urls import path

from .document_views import (
    ClientDocumentCreateView,
    DocumentCreateView,
    DocumentRegenerateView,
    DocumentReviewView,
    DocumentsView,
)
from .views import (
    AdminDataHelpView,
    ApplicationsView,
    ApprovalsView,
    CalendarView,
    CitiesView,
    ClientsView,
    ClientDocumentReviewDetailView,
    ClientDocumentReviewPortalView,
    ClientDocumentsLoadedPortalView,
    ClientDocumentsView,
    ClientExamPortalView,
    ClientFormView,
    ClientChatsView,
    ClientDetailView,
    ClientDiskUploadView,
    ClientQuestionnaireDetailView,
    ClientQuestionnaireEditView,
    ClientQuestionnaireDownloadView,
    ClientQuestionnaireRegenerateView,
    ClientQuestionnaireReviewView,
    ClientPushNotificationCreateView,
    ClientQuestionnairesView,
    CountriesView,
    DocumentActionView,
    DocumentUploadRatingView,
    DashboardView,
    EmployeeReportsView,
    FinanceDealsView,
    FinanceExpenseView,
    FinanceIncomeView,
    FinancePaymentsView,
    FinanceReportsView,
    FinanceView,
    HelpView,
    IncomingLeadsView,
    KnowledgeArticleCreateView,
    KnowledgeArticleView,
    KnowledgeFolderCreateView,
    KnowledgeView,
    LeadDetailView,
    LeadsView,
    NotificationsView,
    OnboardingSubmissionDetailView,
    OnboardingProvisioningRetryView,
    OnboardingSubmissionReviewView,
    OnboardingSubmissionsView,
    NotificationBatchDetailView,
    NotificationCreateView,
    NotificationReadView,
    PortalIndexView,
    PortalLoginView,
    PortalLogoutView,
    ProfileView,
    ProgramsView,
    ProgramFormView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectTaskActionView,
    ProjectTaskCreateView,
    ProjectsView,
    RatingView,
    ReportsView,
    ServicesView,
    SettingsView,
    ServiceFormView,
    TaskFormView,
    TasksView,
    UniversitiesView,
    UniversityDetailView,
    UniversityFormView,
    WorkdayCloseView,
    WorkdayReportView,
    WorkdayReportsView,
    WorkdayStartView,
    WorkdayView,
)

app_name = 'portal'

urlpatterns = [
    path('', PortalIndexView.as_view(), name='index'),
    path('login/', PortalLoginView.as_view(), name='login'),
    path('logout/', PortalLogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('help/', HelpView.as_view(), name='help'),
    path('help/admin-data/', AdminDataHelpView.as_view(), name='admin_data_help'),
    path('leads/', LeadsView.as_view(), name='leads'),
    path('leads/<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('incoming-leads/', IncomingLeadsView.as_view(), name='incoming_leads'),
    path('clients/', ClientsView.as_view(), name='clients'),
    path('client-chats/', ClientChatsView.as_view(), name='client_chats'),
    path('clients/create/', ClientFormView.as_view(), name='client_create'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/disk/upload/', ClientDiskUploadView.as_view(), name='client_disk_upload'),
    path('clients/<int:pk>/exams/', ClientExamPortalView.as_view(), name='client_exam_create'),
    path('clients/<int:pk>/edit/', ClientFormView.as_view(), name='client_edit'),
    path('clients/<int:pk>/documents/create/', ClientDocumentCreateView.as_view(), name='client_document_create'),
    path('client-documents/', ClientDocumentsView.as_view(), name='client_documents'),
    path('client-documents/<int:document_id>/', ClientDocumentReviewDetailView.as_view(), name='client_document_review'),
    path('client-documents/<int:document_id>/action/', ClientDocumentReviewPortalView.as_view(), name='client_document_review_action'),
    path('clients/<int:client_id>/documents-loaded/', ClientDocumentsLoadedPortalView.as_view(), name='client_documents_loaded'),
    path('document-upload-rating/', DocumentUploadRatingView.as_view(), name='document_upload_rating'),
    path('onboarding-submissions/', OnboardingSubmissionsView.as_view(), name='onboarding_submissions'),
    path('onboarding-submissions/<int:pk>/', OnboardingSubmissionDetailView.as_view(), name='onboarding_submission_detail'),
    path('onboarding-submissions/<int:pk>/review/', OnboardingSubmissionReviewView.as_view(), name='onboarding_submission_review'),
    path('onboarding-submissions/<int:pk>/retry/', OnboardingProvisioningRetryView.as_view(), name='onboarding_provisioning_retry'),
    path('client-questionnaires/', ClientQuestionnairesView.as_view(), name='client_questionnaires'),
    path('client-questionnaires/<int:pk>/', ClientQuestionnaireDetailView.as_view(), name='client_questionnaire_detail'),
    path('client-questionnaires/<int:pk>/edit/', ClientQuestionnaireEditView.as_view(), name='client_questionnaire_edit'),
    path('client-questionnaires/<int:pk>/download/', ClientQuestionnaireDownloadView.as_view(), name='client_questionnaire_download'),
    path('client-questionnaires/<int:pk>/regenerate/', ClientQuestionnaireRegenerateView.as_view(), name='client_questionnaire_regenerate'),
    path('client-questionnaires/<int:pk>/review/', ClientQuestionnaireReviewView.as_view(), name='client_questionnaire_review'),
    path('applications/', ApplicationsView.as_view(), name='applications'),
    path('countries/', CountriesView.as_view(), name='countries'),
    path('cities/', CitiesView.as_view(), name='cities'),
    path('universities/', UniversitiesView.as_view(), name='universities'),
    path('universities/create/', UniversityFormView.as_view(), name='university_create'),
    path('universities/<int:pk>/', UniversityDetailView.as_view(), name='university_detail'),
    path('universities/<int:pk>/edit/', UniversityFormView.as_view(), name='university_edit'),
    path('universities/<int:university_pk>/programs/create/', ProgramFormView.as_view(), name='university_program_create'),
    path('programs/', ProgramsView.as_view(), name='programs'),
    path('programs/create/', ProgramFormView.as_view(), name='program_create'),
    path('programs/<int:pk>/edit/', ProgramFormView.as_view(), name='program_edit'),
    path('services/', ServicesView.as_view(), name='services'),
    path('services/create/', ServiceFormView.as_view(), name='service_create'),
    path('services/<int:pk>/edit/', ServiceFormView.as_view(), name='service_edit'),
    path('tasks/', TasksView.as_view(), name='tasks'),
    path('tasks/create/', TaskFormView.as_view(), name='task_create'),
    path('tasks/<int:pk>/edit/', TaskFormView.as_view(), name='task_edit'),
    path('projects/', ProjectsView.as_view(), name='projects'),
    path('projects/create/', ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', ProjectCreateView.as_view(), name='project_edit'),
    path('projects/<int:pk>/tasks/create/', ProjectTaskCreateView.as_view(), name='project_task_create'),
    path('projects/<int:pk>/tasks/<int:task_id>/edit/', ProjectTaskCreateView.as_view(), name='project_task_edit'),
    path('projects/<int:pk>/tasks/<int:task_id>/action/', ProjectTaskActionView.as_view(), name='project_task_action'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('finance/', FinanceView.as_view(), name='finance'),
    path('finance/deals/', FinanceDealsView.as_view(), name='finance_deals'),
    path('finance/payments/', FinancePaymentsView.as_view(), name='finance_payments'),
    path('finance/income/', FinanceIncomeView.as_view(), name='finance_income'),
    path('finance/income/create/', FinanceIncomeView.as_view(), name='finance_income_create'),
    path('finance/expense/', FinanceExpenseView.as_view(), name='finance_expense'),
    path('finance/reports/', FinanceReportsView.as_view(), name='finance_reports'),
    path('approvals/', ApprovalsView.as_view(), name='approvals'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('documents/create/', DocumentCreateView.as_view(), name='document_create'),
    path('documents/<int:pk>/review/', DocumentReviewView.as_view(), name='document_review'),
    path('documents/<int:pk>/regenerate/', DocumentRegenerateView.as_view(), name='document_regenerate'),
    path('documents/<int:pk>/<slug:action>/', DocumentActionView.as_view(), name='document_action'),
    path('knowledge/', KnowledgeView.as_view(), name='knowledge'),
    path('knowledge/folder/<int:pk>/', KnowledgeView.as_view(), name='knowledge_folder'),
    path('knowledge/create-folder/', KnowledgeFolderCreateView.as_view(), name='knowledge_create_folder'),
    path('knowledge/folder/<int:pk>/edit/', KnowledgeFolderCreateView.as_view(), name='knowledge_edit_folder'),
    path('knowledge/create-article/', KnowledgeArticleCreateView.as_view(), name='knowledge_create_article'),
    path('knowledge/article/<int:pk>/', KnowledgeArticleView.as_view(), name='knowledge_article'),
    path('knowledge/article/<int:pk>/edit/', KnowledgeArticleCreateView.as_view(), name='knowledge_edit_article'),
    path('workday/', WorkdayView.as_view(), name='workday'),
    path('workday/reports/', WorkdayReportsView.as_view(), name='workday_reports'),
    path('workday/start/', WorkdayStartView.as_view(), name='workday_start'),
    path('workday/report/', WorkdayReportView.as_view(), name='workday_report'),
    path('workday/close/', WorkdayCloseView.as_view(), name='workday_close'),
    path('rating/', RatingView.as_view(), name='rating'),
    path('employee-reports/', EmployeeReportsView.as_view(), name='employee_reports'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('notifications/create/', NotificationCreateView.as_view(), name='notification_create'),
    path('notifications/clients/create/', ClientPushNotificationCreateView.as_view(), name='client_notification_create'),
    path('notifications/sent/<int:pk>/', NotificationBatchDetailView.as_view(), name='notification_batch_detail'),
    path('notifications/<int:pk>/read/', NotificationReadView.as_view(), name='notification_read'),
    path('reports/', ReportsView.as_view(), name='reports'),
]
