from django.urls import path

from .views import (
    AdminDataHelpView,
    ApplicationsView,
    CalendarView,
    ClientsView,
    DashboardView,
    DocumentsView,
    FinanceExpenseView,
    FinanceIncomeView,
    FinanceReportsView,
    FinanceView,
    HelpView,
    KnowledgeView,
    LeadsView,
    NotificationsView,
    PortalIndexView,
    PortalLoginView,
    PortalLogoutView,
    ProfileView,
    ProgramsView,
    ProjectsView,
    RatingView,
    ReportsView,
    ServicesView,
    SettingsView,
    TasksView,
    UniversitiesView,
    WorkdayCloseView,
    WorkdayReportView,
    WorkdayStartView,
    WorkdayView,
)

app_name = 'portal'

urlpatterns = [
    path('', PortalIndexView.as_view(), name='index'),
    path('login/', PortalLoginView.as_view(), name='login'),
    path('logout/', PortalLogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('help/', HelpView.as_view(), name='help'),
    path('help/admin-data/', AdminDataHelpView.as_view(), name='admin_data_help'),
    path('leads/', LeadsView.as_view(), name='leads'),
    path('clients/', ClientsView.as_view(), name='clients'),
    path('applications/', ApplicationsView.as_view(), name='applications'),
    path('universities/', UniversitiesView.as_view(), name='universities'),
    path('programs/', ProgramsView.as_view(), name='programs'),
    path('services/', ServicesView.as_view(), name='services'),
    path('tasks/', TasksView.as_view(), name='tasks'),
    path('projects/', ProjectsView.as_view(), name='projects'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('finance/', FinanceView.as_view(), name='finance'),
    path('finance/income/', FinanceIncomeView.as_view(), name='finance_income'),
    path('finance/expense/', FinanceExpenseView.as_view(), name='finance_expense'),
    path('finance/reports/', FinanceReportsView.as_view(), name='finance_reports'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('knowledge/', KnowledgeView.as_view(), name='knowledge'),
    path('workday/', WorkdayView.as_view(), name='workday'),
    path('workday/start/', WorkdayStartView.as_view(), name='workday_start'),
    path('workday/report/', WorkdayReportView.as_view(), name='workday_report'),
    path('workday/close/', WorkdayCloseView.as_view(), name='workday_close'),
    path('rating/', RatingView.as_view(), name='rating'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('reports/', ReportsView.as_view(), name='reports'),
]
