# Generated by Django 6.0.2 on 2026-05-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('code', models.SlugField(blank=True, max_length=100, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='active', max_length=32, verbose_name='Status')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_v2', to='organizations.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2', to='organizations.office', verbose_name='Office')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('participants', models.ManyToManyField(blank=True, related_name='projects_v2_participating', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='projects_v2_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible users')),
            ],
            options={
                'verbose_name': 'Project v2',
                'verbose_name_plural': 'Projects v2',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_private', models.BooleanField(db_index=True, default=False, verbose_name='Private')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects_v2.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project note',
                'verbose_name_plural': 'Project notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='Color')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects_v2.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project section',
                'verbose_name_plural': 'Project sections',
                'ordering': ['project__title', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=32, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=32, verbose_name='Priority')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Custom data')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_tasks_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects_v2.projecttask', verbose_name='Parent task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects_v2.project', verbose_name='Project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects_v2.projectsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Project task v2',
                'verbose_name_plural': 'Project tasks v2',
                'ordering': ['project__title', 'section__sort_order', 'sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('link', 'Link')], default='file', max_length=32, verbose_name='Attachment type')),
                ('file', models.FileField(blank=True, null=True, upload_to='erp/projects_v2/task_attachments/', verbose_name='File')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects_v2.projecttask', verbose_name='Task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Task attachment',
                'verbose_name_plural': 'Task attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects_v2.projecttask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task checklist',
                'verbose_name_plural': 'Task checklists',
                'ordering': ['task__title', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_done', models.BooleanField(db_index=True, default=False, verbose_name='Done')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Done at')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects_v2.taskchecklist', verbose_name='Checklist')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_checklist_items_done', to=settings.AUTH_USER_MODEL, verbose_name='Done by')),
            ],
            options={
                'verbose_name': 'Task checklist item',
                'verbose_name_plural': 'Task checklist items',
                'ordering': ['checklist__title', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Text')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_v2_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects_v2.projecttask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task comment',
                'verbose_name_plural': 'Task comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='projects_v2.projecttask', verbose_name='Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_v2_watched_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task watcher',
                'verbose_name_plural': 'Task watchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'office', 'status'], name='projects_v2_company_1388e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='projects_v2_owner_i_cd058b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_v2_created_862573_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='projects_v2_title_8af24d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', 'is_private'], name='projects_v2_project_1a470b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['author', 'created_at'], name='projects_v2_author__95327e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsection',
            index=models.Index(fields=['project', 'is_active'], name='projects_v2_project_ebde12_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsection',
            index=models.Index(fields=['sort_order'], name='projects_v2_sort_or_b0d4bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsection',
            unique_together={('project', 'title')},
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='projects_v2_project_831dba_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['section', 'status'], name='projects_v2_section_62e143_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_to', 'status'], name='projects_v2_assigne_2a77c2_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['deadline'], name='projects_v2_deadlin_2e5765_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['title'], name='projects_v2_title_9ce82e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', 'created_at'], name='projects_v2_task_id_740c60_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='projects_v2_uploade_463193_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchecklist',
            index=models.Index(fields=['task', 'sort_order'], name='projects_v2_task_id_7a7854_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchecklistitem',
            index=models.Index(fields=['checklist', 'is_done'], name='projects_v2_checkli_16c175_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='projects_v2_task_id_5116d6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['author', 'created_at'], name='projects_v2_author__03e03a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskwatcher',
            index=models.Index(fields=['task', 'user'], name='projects_v2_task_id_0b6a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskwatcher',
            index=models.Index(fields=['user', 'created_at'], name='projects_v2_user_id_beb06d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskwatcher',
            unique_together={('task', 'user')},
        ),
    ]
