# Generated by Django 6.0.2 on 2026-05-20 10:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeaccess',
            options={'verbose_name': 'Права сотрудника', 'verbose_name_plural': 'Права сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['company__name', 'office__city', 'user__first_name', 'user__last_name'], 'verbose_name': 'Профиль сотрудника', 'verbose_name_plural': 'Профили сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeerating',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'История рейтинга', 'verbose_name_plural': 'История рейтинга'},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={'ordering': ['name'], 'verbose_name': 'Роль сотрудника', 'verbose_name_plural': 'Роли сотрудников'},
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_be_in_leaderboard',
            field=models.BooleanField(default=True, verbose_name='Показывать в рейтинге'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_manage_catalog',
            field=models.BooleanField(default=False, verbose_name='Может управлять каталогом вузов'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_manage_documents',
            field=models.BooleanField(default=False, verbose_name='Может управлять документами'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_manage_finance',
            field=models.BooleanField(default=False, verbose_name='Может управлять финансами'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_manage_hr',
            field=models.BooleanField(default=False, verbose_name='Может управлять сотрудниками'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_see_all_company',
            field=models.BooleanField(default=False, verbose_name='Видит всю компанию'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='can_see_all_office',
            field=models.BooleanField(default=False, verbose_name='Видит весь офис'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='employees.employeeprofile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Процент комиссии'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='fired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Оклад USD'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.employeerole', verbose_name='Роль доступа'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фиксированный оклад'), ('commission', 'Только комиссия'), ('mixed', 'Оклад + комиссия')], default='mixed', max_length=32, verbose_name='Тип зарплаты'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='work_status',
            field=models.CharField(choices=[('working', 'Работает'), ('vacation', 'В отпуске'), ('sick', 'На больничном'), ('fired', 'Уволен'), ('paused', 'Приостановлен')], default='working', max_length=32, verbose_name='Рабочий статус'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_logs', to='employees.employeeprofile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='code',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Код роли'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role_type',
            field=models.CharField(choices=[('company_owner', 'Владелец компании'), ('office_director', 'Директор офиса'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('hr', 'HR'), ('viewer', 'Наблюдатель')], db_index=True, max_length=32, verbose_name='Тип роли'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
