# Generated by Django 6.0.2 on 2026-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeaccess_must_track_workday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccess',
            name='rating_priority_enabled',
            field=models.BooleanField(default=False, verbose_name='Приоритет в рейтинге'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='rating_priority_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень приоритета в рейтинге'),
        ),
        migrations.AddField(
            model_name='employeeaccess',
            name='rating_priority_note',
            field=models.TextField(blank=True, verbose_name='Комментарий к приоритету'),
        ),
    ]
