# Generated by Django 6.0.2 on 2026-08-05 05:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0012_client_academic_year_client_sl_id'),
        ('education', '0003_country_city_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('kind', models.CharField(choices=[('applicant', 'Абитуриент'), ('school_student', 'Школьник')], max_length=24, verbose_name='Тип')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
            ],
            options={
                'verbose_name': 'Счётчик SL-ID',
                'verbose_name_plural': 'Счётчики SL-ID',
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'kind'), name='uniq_sl_id_sequence_year_kind')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('access_token_hash', models.CharField(editable=False, max_length=64, verbose_name='Хеш токена анкеты')),
                ('kind', models.CharField(choices=[('applicant', 'Абитуриент'), ('school_student', 'Школьник')], max_length=24, verbose_name='Тип анкеты')),
                ('academic_year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год поступления')),
                ('status', models.CharField(choices=[('submitted', 'Отправлена'), ('changes_requested', 'Требуются исправления'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='submitted', max_length=24, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(db_index=True, max_length=80, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=120, verbose_name='Гражданство')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Остальные данные анкеты')),
                ('fcm_token', models.TextField(blank=True, verbose_name='Firebase token')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_submission', to='crm.client', verbose_name='Созданный клиент')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Анкета из приложения',
                'verbose_name_plural': 'Анкеты из приложения',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingUniversityChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Приоритет')),
                ('programs', models.ManyToManyField(related_name='onboarding_choices', to='education.program', verbose_name='Программы')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_choices', to='client_onboarding.onboardingsubmission', verbose_name='Анкета')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_choices', to='education.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Выбор ВУЗа в анкете',
                'verbose_name_plural': 'Выборы ВУЗов в анкетах',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='client_onbo_status_cd22d7_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingsubmission',
            index=models.Index(fields=['academic_year', 'kind'], name='client_onbo_academi_6b68f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardinguniversitychoice',
            constraint=models.UniqueConstraint(fields=('submission', 'university'), name='uniq_onboarding_submission_university'),
        ),
        migrations.AddConstraint(
            model_name='onboardinguniversitychoice',
            constraint=models.UniqueConstraint(fields=('submission', 'rank'), name='uniq_onboarding_submission_rank'),
        ),
    ]
