# Generated by Django 6.0.2 on 2026-08-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0001_initial'),
        ('crm', '0012_client_academic_year_client_sl_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлена'), ('in_review', 'На проверке'), ('changes_requested', 'Требуются исправления'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='submitted', max_length=24, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ClientServiceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('mobile_login', models.CharField(max_length=32, unique=True, verbose_name='Логин Students Life')),
                ('shared_password', models.CharField(max_length=128, verbose_name='Единый пароль')),
                ('tmmail_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Адрес TMmail')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_identity', to='crm.client', verbose_name='Клиент')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_identity', to='client_onboarding.onboardingsubmission', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Учётные данные сервисов клиента',
                'verbose_name_plural': 'Учётные данные сервисов клиентов',
            },
        ),
        migrations.CreateModel(
            name='OnboardingReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('decision', models.CharField(choices=[('start_review', 'Взята на проверку'), ('approve', 'Одобрена'), ('request_changes', 'Возвращена на исправление'), ('reject', 'Отклонена'), ('resubmit', 'Повторно отправлена')], max_length=32, verbose_name='Решение')),
                ('from_status', models.CharField(max_length=24, verbose_name='Предыдущий статус')),
                ('to_status', models.CharField(max_length=24, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_review_events', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='client_onboarding.onboardingsubmission', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Событие проверки анкеты',
                'verbose_name_plural': 'История проверки анкет',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['submission', 'created_at'], name='client_onbo_submiss_96f018_idx')],
            },
        ),
    ]
