# Generated by Django 6.0.2 on 2026-08-08 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0002_alter_onboardingsubmission_status_and_more'),
        ('crm', '0012_client_academic_year_client_sl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProvisioningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('step', models.CharField(choices=[('mobile_account', 'Аккаунт Students Life'), ('tmmail', 'Почтовый ящик TMmail')], max_length=32, verbose_name='Шаг')),
                ('status', models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('success', 'Готово'), ('failed', 'Ошибка'), ('disabled', 'Сервис не настроен'), ('not_required', 'Не требуется')], db_index=True, default='pending', max_length=24, verbose_name='Статус')),
                ('event_id', models.CharField(max_length=120, unique=True, verbose_name='Ключ идемпотентности')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало попытки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Ответ сервиса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_steps', to='crm.client', verbose_name='Клиент')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_steps', to='client_onboarding.onboardingsubmission', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Шаг подключения сервиса',
                'verbose_name_plural': 'Шаги подключения сервисов',
                'ordering': ['submission_id', 'step'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='client_onbo_status_c3372f_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'step'), name='uniq_client_provisioning_submission_step')],
            },
        ),
    ]
