# Generated by Django 6.0.2 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0004_onboardingsubmission_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprovisioningstep',
            name='step',
            field=models.CharField(
                choices=[
                    ('mobile_account', 'Аккаунт Students Life'),
                    ('tmmail', 'Почтовый ящик TMmail'),
                    ('disk', 'Папки клиента на диске'),
                ],
                max_length=32,
                verbose_name='Шаг',
            ),
        ),
    ]
