# Generated by Django 5.1.7 on 2026-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0005_alter_clientprovisioningstep_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsubmission',
            name='telegram_sent_parts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='onboardingreviewevent',
            name='decision',
            field=models.CharField(choices=[('start_review', 'Взята на проверку'), ('approve', 'Одобрена'), ('request_changes', 'Возвращена на исправление'), ('reject', 'Отклонена'), ('resubmit', 'Повторно отправлена'), ('process', 'Обработано без создания клиента')], max_length=32, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлена'), ('in_review', 'На проверке'), ('changes_requested', 'Требуются исправления'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('processed', 'Обработано')], db_index=True, default='submitted', max_length=24, verbose_name='Статус'),
        ),
    ]
