# Generated by Django 6.0.2 on 2026-02-22 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата смены')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время прихода')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Смена активна (В офисе)')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Отработано часов')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Учет рабочего времени',
                'ordering': ['-date', '-time_in'],
            },
        ),
    ]
