# Generated by Django 6.0.2 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='is_auto_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто автоматически (Забыл уйти)'),
        ),
    ]
