# Generated by Django 6.0.2 on 2026-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_workshift_is_auto_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
