QUESTIONNAIRE_VALUE_LABELS = {
    'male': 'Мужской',
    'female': 'Женский',
    'school_student': 'Школьник / предварительная заявка',
    'applicant': 'Абитуриент / полная анкета',
    True: 'Да',
    False: 'Нет',
}


QUESTIONNAIRE_DOCUMENT_LABELS = {
    'full_name': 'ФИО',
    'birth_date': 'Дата рождения',
    'gender': 'Пол',
    'citizenship': 'Гражданство',
    'marital_status': 'Семейное положение',
    'residence_country': 'Страна',
    'residence_region': 'Регион',
    'residence_city': 'Город',
    'residence_street': 'Улица',
    'residence_house': 'Дом / квартира',
    'residence_postal_code': 'Почтовый индекс',
    'passport_number': 'Паспорт',
    'passport_issued_by': 'Где оформлен',
    'passport_issue_date': 'Дата начала действия',
    'passport_expiry_date': 'Дата окончания действия',
    'has_international_passport': 'Загранпаспорт',
    'phone': 'Телефон',
    'email': 'Email',
    'extra_phone': 'Доп. телефон',
    'imo': 'Imo',
    'telegram': 'Telegram',
    'preferred_contact_method': 'Способ связи',
    'parent_full_name': 'ФИО родителя',
    'parent_relation': 'Кем является',
    'parent_contacts': 'Контакты родителя',
    'parent_workplace': 'Работа родителя',
    'family_members': 'Семья',
    'education_level': 'Уровень образования',
    'school_class': 'Класс',
    'school_name': 'Учебное заведение',
    'school_country': 'Страна учебы',
    'school_city': 'Город учебы',
    'graduation_year': 'Год окончания',
    'education_status': 'Статус',
    'languages': 'Языки',
    'desired_program': 'Программа / Вуз',
    'admission_goal': 'Цель',
    'desired_city': 'Город',
    'desired_country': 'Страна',
    'desired_language': 'Язык обучения',
    'desired_education_level': 'Уровень обучения',
    'admission_urgency': 'Срочность',
    'has_visa': 'Виза',
    'visa_country': 'Страна визы',
    'visa_city': 'Город визы',
    'visa_valid_until': 'Срок визы',
    'hobbies': 'Хобби',
    'applicant_comment': 'Комментарий',
    'referral_source': 'Источник',
    'data_processing_consent': 'Согласие на обработку данных',
    'status': 'Статус анкеты',
    'generated_document_at': 'Дата формирования',
}
