# Generated by Django 6.0.2 on 2026-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fcm_message_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_office_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('first_place_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Рейтинг (Архив)',
                'verbose_name_plural': 'Рейтинги (Архив)',
            },
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tutorials/', verbose_name='Файл видео')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Или ссылка на YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
            },
        ),
    ]
