# Generated by Django 6.0.2 on 2026-02-14 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_initial'),
        ('gamification', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='first_place_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_medals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialperiod', verbose_name='За период'),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='second_place_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silver_medals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='third_place_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bronze_medals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='top_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.office'),
        ),
    ]
