# Generated by Django 6.0.2 on 2026-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        ('users', '0002_managersalary_commission_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
            ],
            options={
                'verbose_name': '🏆 Рейтинг (Текущий)',
                'verbose_name_plural': '🏆 Рейтинг (Текущий)',
                'ordering': ('-managersalary__current_month_revenue',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='second_place_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка 2 места'),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='third_place_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка 3 места'),
        ),
        migrations.AlterField(
            model_name='ratingsnapshot',
            name='first_place_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка 1 места'),
        ),
    ]
