# Generated by Django 6.0.2 on 2026-02-15 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_leaderboard_ratingsnapshot_second_place_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsnapshot',
            name='second_place_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silver_medals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingsnapshot',
            name='third_place_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bronze_medals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingsnapshot',
            name='top_office_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Выручка офиса'),
        ),
    ]
