# Generated by Django 6.0.2 on 2026-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_ratingsnapshot_second_place_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ratingsnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
